#!r6rs
(import (chezscheme) (theourgia rpc) (theourgia store) (theourgia reduce) (theourgia ffi)
        (theourgia log) (theourgia code-project) (theourgia code-markers) (theourgia languages))
(define bad 0)
(define (want name got expected)
  (if (equal? got expected) (printf "ok ~a\n" name)
      (begin (set! bad (+ bad 1)) (printf "FAIL ~a: ~s WANT ~s\n" name got expected))))
(define root (string-append (or (getenv "THEOURGIA_TEST_ROOT") "/tmp") "/code-import-" (number->string (get-process-id))))
(mkdir-p! root)
(putenv "THEOURGIA_HOME" (string-append root "/home"))
(define counter 0)
(define py (language-for-name 'python))
(define one (string->utf8 "# first\ndef f():\n  pass\n"))
(define two (string->utf8 "def g():\n  pass"))
(define changed (string->utf8 "# changed docs\ndef renamed():\n  return 1"))
(define (write! path b)
  (call-with-port (open-file-output-port path (file-options no-fail)) (lambda (p) (put-bytevector p b))))
(define (fresh)
  (set! counter (+ counter 1))
  (let* ((dir (string-append root "/case-" (number->string counter))) (store (string-append dir "/store"))
         (input (string-append dir "/input")) (edit (string-append dir "/edit")))
    (mkdir-p! input) (mkdir-p! edit) (rpc-dispatch store '(init) "test")
    (write! (string-append input "/a.py") (projection-encode py #f (list (list "new" one) (list "new" two))))
    (write! (string-append input "/b.py") (string->utf8 "def unrelated():\n  pass\n"))
    (unless (rpc-ok? (rpc-dispatch store (list 'import-code input) "test")) (error 'fixture "Initial import failed"))
    (let* ((s (open-and-reduce store))
           (a (find (lambda (id) (equal? (code-field s id 'path) "a.py")) (code-files s)))
           (b (find (lambda (id) (equal? (code-field s id 'path) "b.py")) (code-files s))))
      (list store edit a (code-children s a) b s))))
(define (header c) (list (store-id-of (car c)) (list-ref c 2) (reduce-applied-cut (list-ref c 5))))
(define (edit! c entries . head)
  (write! (string-append (cadr c) "/a.py") (projection-encode py (if (pair? head) (car head) (header c)) entries)))
(define (run c . allow)
  (rpc-dispatch (car c) (append (list 'import-code (cadr c)) (if (pair? allow) '("--allow-delete") '())) "test"))
(define (reason a) (let ((p (and (list? a) (assq 'reason (filter pair? a))))) (and p (cadr p))))
(define (src c id) (code-field (open-and-reduce (car c)) id 'src))
(for-each
  (lambda (cause)
    (let* ((c (fresh)) (ids (list-ref c 3)) (h (header c)) (store (car c))
           (foreign (car (code-children (list-ref c 5) (list-ref c 4))))
           (last (case cause ((duplicate-id) (car ids)) ((foreign-file) foreign) (else (cadr ids)))))
      (when (eq? cause 'tombstone)
        (with-store-write store (lambda (s v) (list (list 'del (cadr ids)))) "test")
        (set! h (list (car h) (cadr h) (reduce-applied-cut (open-and-reduce store)))))
      (when (eq? cause 'foreign-store) (set! h (cons "another-store" (cdr h))))
      (when (eq? cause 'unavailable-cut) (set! h (list (car h) (cadr h) '(("missing-writer" . 999)))))
      (edit! c (list (list (car ids) changed) (list last two)) h)
      (let* ((before (reduce-applied-cut (open-and-reduce store))) (a (run c)))
        (want (string-append "CT-08 refusal reason " (symbol->string cause)) (reason a) cause)
        (want (string-append "CT-08 no earlier append on " (symbol->string cause)) (reduce-applied-cut (open-and-reduce store)) before)
        (want "CT-08 earlier source is untouched" (src c (car ids)) one))))
  '(duplicate-id foreign-file foreign-store tombstone unavailable-cut))
(let* ((c (fresh)) (ids (list-ref c 3)))
  (edit! c (list (list (car ids) changed) (list (cadr ids) two)))
  (want "CT-08 correct scoped IDs permit the same earlier edit" (rpc-ok? (run c)) #t)
  (let ((s (open-and-reduce (car c))))
    (want "CT-10 source changes by ID" (code-field s (car ids) 'src) changed)
    (want "CT-06 derived name changes with source" (code-field s (car ids) 'name) "renamed")
    (want "CT-06 derived doc changes with source" (code-field s (car ids) 'doc) (string->utf8 "# changed docs\n")))
  (want "CT-06 independent doc writes are refused" (cadr (rpc-dispatch (car c) (list 'set (car ids) "doc" "wrong") "test")) 'derived-field)
  (want "CT-06 direct set src succeeds" (rpc-ok? (rpc-dispatch (car c) (list 'set (car ids) "src" "# direct\ndef direct():\n  pass") "test")) #t)
  (let ((s (open-and-reduce (car c))))
    (want "CT-06 direct set stores bytes" (code-field s (car ids) 'src) (string->utf8 "# direct\ndef direct():\n  pass"))
    (want "CT-06 direct set recomputes name" (code-field s (car ids) 'name) "direct")
    (want "CT-06 direct set recomputes doc" (code-field s (car ids) 'doc) (string->utf8 "# direct\n"))))
(for-each
  (lambda (related?)
    (let* ((c (fresh)) (ids (list-ref c 3)) (local (if related? (car ids) (car (code-children (list-ref c 5) (list-ref c 4))))))
      (edit! c (list (list (car ids) one) (list (cadr ids) changed)))
      (with-store-write (car c) (lambda (s v) (list (list 'set local 'src (string->utf8 "local edit")))) "test")
      (let* ((before (reduce-applied-cut (open-and-reduce (car c)))) (a (run c)))
        (want (if related? "CT-11 related change refuses whole import" "CT-11 unrelated change permits import") (rpc-ok? a) (not related?))
        (when related?
          (want "CT-11 stale import has no business event" (reduce-applied-cut (open-and-reduce (car c))) before)
          (want "CT-11 carried block cannot erase newer bytes" (src c local) (string->utf8 "local edit")))))) '(#t #f))
(let* ((c (fresh)) (ids (list-ref c 3)))
  (edit! c (list (list (cadr ids) two) (list (car ids) one)))
  (want "CT-10 reorder succeeds" (rpc-ok? (run c)) #t)
  (want "CT-10 marker order is authoritative" (code-children (open-and-reduce (car c)) (list-ref c 2)) (reverse ids)))
(let* ((c (fresh)) (ids (list-ref c 3)))
  (edit! c (list (list (car ids) one)))
  (want "CT-10 deletion requires explicit option" (reason (run c)) 'would-delete)
  (want "CT-10 approved deletion succeeds" (rpc-ok? (run c #t)) #t)
  (want "CT-10 absent marker tombstones former child" (cdr (assq 'deleted (state-read (open-and-reduce (car c)) (cadr ids)))) #t))
(let* ((c (fresh)) (ids (list-ref c 3)))
  (write! (string-append (cadr c) "/renamed.py") (projection-encode py (header c) (list (list (car ids) one) (list (cadr ids) two))))
  (want "CT-10 path-only update succeeds" (rpc-ok? (run c)) #t)
  (want "CT-10 header identifies renamed file" (code-field (open-and-reduce (car c)) (list-ref c 2) 'path) "renamed.py"))
(let* ((c (fresh)) (ids (list-ref c 3)))
  (write! (string-append (cadr c) "/a.py") one)
  (want "CT-09 unmarked same name creates new identity" (rpc-ok? (run c)) #t)
  (want "CT-09 original file retains original children" (code-children (open-and-reduce (car c)) (list-ref c 2)) ids)
  (want "CT-09 path is not identity evidence" (length (code-files (open-and-reduce (car c)))) 3)
  (want "CT-09 duplicate output paths refuse export" (reason (rpc-dispatch (car c) (list 'export-code (string-append (cadr c) "/out")) "test")) 'duplicate-path))
(let* ((c (fresh)) (ids (list-ref c 3)) (after (car (reduce-applied-cut (list-ref c 5))))
       (req (make-write-request "test" 'import-code (list (cadr c)) "import-once" after)))
  (edit! c (list (list (car ids) changed) (list (cadr ids) two)))
  (want "CT-identity first captured operation commits" (rpc-ok? (import-code (car c) (cadr c) "test" req #f)) #t)
  (write! (string-append (cadr c) "/a.py") (string->utf8 "a different mutable file"))
  (let* ((before (reduce-applied-cut (open-and-reduce (car c)))))
    (want "CT-identity retry uses original immutable bytes" (rpc-ok? (import-code (car c) (cadr c) "test" req #f)) #t)
    (want "CT-identity retry appends no duplicate operation" (reduce-applied-cut (open-and-reduce (car c))) before)
    (want "CT-identity changed actor refuses reused identity"
          (import-code (car c) (cadr c) "other" (make-write-request "other" 'import-code (list (cadr c)) "import-once" after) #f)
          '(error req-mismatch))))
(let* ((c (fresh)) (ids (list-ref c 3)) (after (car (reduce-applied-cut (list-ref c 5))))
       (cursor (string-append (car after) ":" (number->string (cdr after)))))
  (edit! c (list (list (car ids) changed) (list (cadr ids) two)))
  (want "CT-identity RPC accepts an explicit import identity"
        (rpc-ok? (rpc-dispatch (car c) (list 'import-code (cadr c) "--req" "rpc-import" "--cursor" cursor) "test")) #t))
(let* ((c (fresh)) (ids (list-ref c 3)))
  (write! (string-append (cadr c) "/renamed.js") (projection-encode py (header c) (list (list (car ids) one) (list (cadr ids) two))))
  (want "CT-10 extension rename keeps the existing header identity" (rpc-ok? (run c)) #t)
  (let ((state (open-and-reduce (car c))))
    (want "CT-10 extension rename updates file path" (code-field state (list-ref c 2) 'path) "renamed.js")
    (want "CT-10 extension rename updates language from table" (code-field state (car ids) 'lang) 'javascript)))
(let* ((c (fresh)) (ids (list-ref c 3)))
  (edit! c (list (list (car ids) one) (list (cadr ids) two)))
  (with-store-write (car c)
    (lambda (s v) (list (list 'insert (list-ref c 2) #f '((kind . code) (mode . text) (src . #vu8()))))) "test")
  (want "CT-11 newly added child invalidates the captured file membership" (rpc-ok? (run c)) #f))
(let* ((c (fresh)) (output (string-append (cadr c) "/out")))
  (with-store-write (car c)
    (lambda (s v) (list '(insert root #f ((kind . file) (mode . datum) (path . "library.sc"))))) "test")
  (want "CT-12 text export selects only text files" (rpc-ok? (rpc-dispatch (car c) (list 'export-code output) "test")) #t)
  (want "CT-12 text export excludes datum file" (file-exists? (string-append output "/library.sc")) #f)
  (want "CT-12 explicit in-place mode change is refused"
        (map cadr (with-store-write (car c) (lambda (s v) (list (list 'set (list-ref c 2) 'mode 'datum))) "test"))
        '(mode-mismatch)))
(printf "~a failures\ncode-import complete\n" bad)
(exit (if (zero? bad) 0 1))
