#!r6rs
(import (chezscheme) (theourgia rpc) (theourgia store) (theourgia reduce) (theourgia ffi)
        (theourgia log) (theourgia code-project) (theourgia code-markers) (theourgia languages))
(define bad 0)
(define (want name got expected)
  (if (equal? got expected) (printf "ok ~a\n" name)
      (begin (set! bad (+ bad 1)) (printf "FAIL ~a: ~s WANT ~s\n" name got expected))))
(define root (string-append (or (getenv "THEOURGIA_TEST_ROOT") "/tmp") "/code-import-" (number->string (get-process-id))))
(mkdir-p! root)
(putenv "THEOURGIA_HOME" (string-append root "/home"))
(define counter 0)
(define py (language-for-name 'python))
(define one (string->utf8 "# first\ndef f():\n  pass\n"))
(define two (string->utf8 "def g():\n  pass"))
(define changed (string->utf8 "# changed docs\ndef renamed():\n  return 1"))
(define (write! path b)
  (call-with-port (open-file-output-port path (file-options no-fail)) (lambda (p) (put-bytevector p b))))
(define (fresh)
  (set! counter (+ counter 1))
  (let* ((dir (string-append root "/case-" (number->string counter))) (store (string-append dir "/store"))
         (input (string-append dir "/input")) (edit (string-append dir "/edit")))
    (mkdir-p! input) (mkdir-p! edit) (rpc-dispatch store '(init) "test")
    (write! (string-append input "/a.py") (projection-encode py #f (list (list "new" one) (list "new" two))))
    (write! (string-append input "/b.py") (string->utf8 "def unrelated():\n  pass\n"))
    (unless (rpc-ok? (rpc-dispatch store (list 'import-code input) "test")) (error 'fixture "Initial import failed"))
    (let* ((s (open-and-reduce store))
           (a (find (lambda (id) (equal? (code-field s id 'path) "a.py")) (code-files s)))
           (b (find (lambda (id) (equal? (code-field s id 'path) "b.py")) (code-files s))))
      (list store edit a (code-children s a) b s))))
(define (header c) (list (store-id-of (car c)) (list-ref c 2) (reduce-applied-cut (list-ref c 5))))
(define (edit! c entries . head)
  (write! (string-append (cadr c) "/a.py") (projection-encode py (if (pair? head) (car head) (header c)) entries)))
(define (run c . allow)
  (rpc-dispatch (car c) (append (list 'import-code (cadr c)) (if (pair? allow) '("--allow-delete") '())) "test"))
(define (reason a) (let ((p (and (list? a) (assq 'reason (filter pair? a))))) (and p (cadr p))))
(define (src c id) (code-field (open-and-reduce (car c)) id 'src))
(for-each
  (lambda (cause)
    (let* ((c (fresh)) (ids (list-ref c 3)) (h (header c)) (store (car c))
           (foreign (car (code-children (list-ref c 5) (list-ref c 4))))
           (last (case cause ((duplicate-id) (car ids)) ((foreign-file) foreign) (else (cadr ids)))))
      (when (eq? cause 'tombstone)
        (with-store-write store (lambda (s v) (list (list 'del (cadr ids)))) "test")
        (set! h (list (car h) (cadr h) (reduce-applied-cut (open-and-reduce store)))))
      (when (eq? cause 'foreign-store) (set! h (cons "another-store" (cdr h))))
      (when (eq? cause 'unavailable-cut) (set! h (list (car h) (cadr h) '(("missing-writer" . 999)))))
      (edit! c (list (list (car ids) changed) (list last two)) h)
      (let* ((before (reduce-applied-cut (open-and-reduce store))) (a (run c)))
        (want (string-append "CT-08 refusal reason " (symbol->string cause)) (reason a) cause)
        (want (string-append "CT-08 no earlier append on " (symbol->string cause)) (reduce-applied-cut (open-and-reduce store)) before)
        (want "CT-08 earlier source is untouched" (src c (car ids)) one))))
  '(duplicate-id foreign-file foreign-store tombstone unavailable-cut))
(let* ((c (fresh)) (ids (list-ref c 3)))
  (edit! c (list (list (car ids) changed) (list (cadr ids) two)))
  (want "CT-08 correct scoped IDs permit the same earlier edit" (rpc-ok? (run c)) #t)
  (let ((s (open-and-reduce (car c))))
    (want "CT-10 source changes by ID" (code-field s (car ids) 'src) changed)
    (want "CT-06 derived name changes with source" (code-field s (car ids) 'name) "renamed")
    (want "CT-06 derived doc changes with source" (code-field s (car ids) 'doc) (string->utf8 "# changed docs\n")))
  (want "CT-06 independent doc writes are refused" (cadr (rpc-dispatch (car c) (list 'set (car ids) "doc" "wrong") "test")) 'derived-field)
  (want "CT-06 direct set src succeeds" (rpc-ok? (rpc-dispatch (car c) (list 'set (car ids) "src" "# direct\ndef direct():\n  pass") "test")) #t)
  (let ((s (open-and-reduce (car c))))
    (want "CT-06 direct set stores bytes" (code-field s (car ids) 'src) (string->utf8 "# direct\ndef direct():\n  pass"))
    (want "CT-06 direct set recomputes name" (code-field s (car ids) 'name) "direct")
    (want "CT-06 direct set recomputes doc" (code-field s (car ids) 'doc) (string->utf8 "# direct\n"))))
(for-each
  (lambda (related?)
    (let* ((c (fresh)) (ids (list-ref c 3)) (local (if related? (car ids) (car (code-children (list-ref c 5) (list-ref c 4))))))
      (edit! c (list (list (car ids) one) (list (cadr ids) changed)))
      (with-store-write (car c) (lambda (s v) (list (list 'set local 'src (string->utf8 "local edit")))) "test")
      (let* ((before (reduce-applied-cut (open-and-reduce (car c)))) (a (run c)))
        (want (if related? "CT-11 related change refuses whole import" "CT-11 unrelated change permits import") (rpc-ok? a) (not related?))
        (when related?
          (want "CT-11 stale import has no business event" (reduce-applied-cut (open-and-reduce (car c))) before)
          (want "CT-11 carried block cannot erase newer bytes" (src c local) (string->utf8 "local edit")))))) '(#t #f))
(let* ((c (fresh)) (ids (list-ref c 3)))
  (edit! c (list (list (cadr ids) two) (list (car ids) one)))
  (want "CT-10 reorder succeeds" (rpc-ok? (run c)) #t)
  (want "CT-10 marker order is authoritative" (code-children (open-and-reduce (car c)) (list-ref c 2)) (reverse ids)))
(let* ((c (fresh)) (ids (list-ref c 3)))
  (edit! c (list (list (car ids) one)))
  (want "CT-10 deletion requires explicit option" (reason (run c)) 'would-delete)
  (want "CT-10 approved deletion succeeds" (rpc-ok? (run c #t)) #t)
  (want "CT-10 absent marker tombstones former child" (cdr (assq 'deleted (state-read (open-and-reduce (car c)) (cadr ids)))) #t))
(let* ((c (fresh)) (ids (list-ref c 3)))
  (write! (string-append (cadr c) "/renamed.py") (projection-encode py (header c) (list (list (car ids) one) (list (cadr ids) two))))
  (want "CT-10 path-only update succeeds" (rpc-ok? (run c)) #t)
  (want "CT-10 header identifies renamed file" (code-field (open-and-reduce (car c)) (list-ref c 2) 'path) "renamed.py"))
(let* ((c (fresh)) (ids (list-ref c 3)))
  (write! (string-append (cadr c) "/a.py") one)
  (want "CT-09 unmarked same name creates new identity" (rpc-ok? (run c)) #t)
  (want "CT-09 original file retains original children" (code-children (open-and-reduce (car c)) (list-ref c 2)) ids)
  (want "CT-09 path is not identity evidence" (length (code-files (open-and-reduce (car c)))) 3)
  (want "CT-09 duplicate output paths refuse export" (reason (rpc-dispatch (car c) (list 'export-code (string-append (cadr c) "/out")) "test")) 'duplicate-path))
(let* ((c (fresh)) (ids (list-ref c 3)) (after (car (reduce-applied-cut (list-ref c 5))))
       (req (make-write-request "test" 'import-code (list (cadr c)) "import-once" after)))
  (edit! c (list (list (car ids) changed) (list (cadr ids) two)))
  (want "CT-identity first captured operation commits" (rpc-ok? (import-code (car c) (cadr c) "test" req #f)) #t)
  (write! (string-append (cadr c) "/a.py") (string->utf8 "a different mutable file"))
  (let* ((before (reduce-applied-cut (open-and-reduce (car c)))))
    (want "CT-identity retry uses original immutable bytes" (rpc-ok? (import-code (car c) (cadr c) "test" req #f)) #t)
    (want "CT-identity retry appends no duplicate operation" (reduce-applied-cut (open-and-reduce (car c))) before)
    (want "CT-identity changed actor refuses reused identity"
          (import-code (car c) (cadr c) "other" (make-write-request "other" 'import-code (list (cadr c)) "import-once" after) #f)
          '(error req-mismatch))))
(let* ((c (fresh)) (ids (list-ref c 3)) (after (car (reduce-applied-cut (list-ref c 5))))
       (cursor (string-append (car after) ":" (number->string (cdr after)))))
  (edit! c (list (list (car ids) changed) (list (cadr ids) two)))
  (want "CT-identity RPC accepts an explicit import identity"
        (rpc-ok? (rpc-dispatch (car c) (list 'import-code (cadr c) "--req" "rpc-import" "--cursor" cursor) "test")) #t))
(let* ((c (fresh)) (ids (list-ref c 3)))
  (write! (string-append (cadr c) "/renamed.js") (projection-encode py (header c) (list (list (car ids) one) (list (cadr ids) two))))
  (want "CT-10 extension rename keeps the existing header identity" (rpc-ok? (run c)) #t)
  (let ((state (open-and-reduce (car c))))
    (want "CT-10 extension rename updates file path" (code-field state (list-ref c 2) 'path) "renamed.js")
    (want "CT-10 extension rename updates language from table" (code-field state (car ids) 'lang) 'javascript)))
(let* ((c (fresh)) (ids (list-ref c 3)))
  (edit! c (list (list (car ids) one) (list (cadr ids) two)))
  (with-store-write (car c)
    (lambda (s v) (list (list 'insert (list-ref c 2) #f '((kind . code) (mode . text) (src . #vu8()))))) "test")
  (want "CT-11 newly added child invalidates the captured file membership" (rpc-ok? (run c)) #f))
(let* ((c (fresh)) (output (string-append (cadr c) "/out")))
  (with-store-write (car c)
    (lambda (s v) (list '(insert root #f ((kind . file) (mode . datum) (path . "library.sc"))))) "test")
  (want "CT-12 text export selects only text files" (rpc-ok? (rpc-dispatch (car c) (list 'export-code output) "test")) #t)
  (want "CT-12 text export excludes datum file" (file-exists? (string-append output "/library.sc")) #f)
  (want "CT-12 explicit in-place mode change is refused"
        (map cadr (with-store-write (car c) (lambda (s v) (list (list 'set (list-ref c 2) 'mode 'datum))) "test"))
        '(mode-mismatch)))
;; Y5: two text paths, each held by two file blocks. The text export
;; refuses once with the same shape as the datum projection: a duplicated
;; path and its own ids, every duplicated path with its ids, and the remedy.
(let* ((c (fresh)) (store (car c)) (out (string-append (cadr c) "/y5-out")))
  (with-store-write store
    (lambda (s v) (list '(insert root #f ((kind . file) (mode . text) (path . "a.py") (lang . python)))
                        '(insert root #f ((kind . file) (mode . text) (path . "b.py") (lang . python)))))
    "test")
  (let* ((st (open-and-reduce store))
         (ha (state-path-claimants st 'file 'text "a.py"))
         (hb (state-path-claimants st 'file 'text "b.py"))
         (a (rpc-dispatch store (list 'export-code out) "test"))
         (clause (lambda (head) (and (list? a) (assq head (filter pair? a))))))
    (want "Y5 export-code of two text paths each held twice refuses once: a duplicated path with its own ids, both paths with their ids, and the remedy"
          (list (and (pair? a) (car a)) (clause 'reason)
                (let ((p (clause 'path)) (i (clause 'ids)))
                  (and p i (equal? (cadr i) (state-path-claimants st 'file 'text (cadr p)))))
                (clause 'paths) (clause 'remedy) (length ha) (length hb))
          (list 'error '(reason duplicate-path) #t
                (list 'paths (list (list "a.py" (list 'ids ha)) (list "b.py" (list 'ids hb))))
                '(remedy del-all-but-one-per-path) 2 2))))
(define (bv-append a b)
  (let ((out (make-bytevector (+ (bytevector-length a) (bytevector-length b)))))
    (bytevector-copy! a 0 out 0 (bytevector-length a))
    (bytevector-copy! b 0 out (bytevector-length a) (bytevector-length b))
    out))
(define (bv-append-ff b) (bv-append b (bytevector 255)))
;; ---- what a text import holds ------------------------------------------------
;;
;; NEVER: A TEXT IMPORT KEEPS WHAT IS TEXT, DECIDED BY THE BYTES. A file that
;; is UTF-8 with no NUL byte is imported as before, a registered extension or
;; not; any other file is not imported and is listed in `(skipped (...))`, in
;; the walk's order, the clause absent when nothing was skipped. The test runs
;; before any projection decoding, so a skipped file touches nothing.
(define (safely thunk)
  (guard (e (#t (list 'RAISED (if (and (condition? e) (message-condition? e)) (condition-message e) e)))) (thunk)))
(define (answer-clause a head)
  (and (pair? a) (list? a) (find (lambda (c) (and (pair? c) (eq? (car c) head))) (cdr a))))
(define (answer-head a)
  (cond ((not (pair? a)) a)
        ((and (eq? (car a) 'error) (pair? (cdr a))) (list 'error (cadr a)))
        (else (car a))))
;; -> (store . input)
(define (text-area! name)
  (let* ((dir (string-append root "/" name)) (store (string-append dir "/store")) (input (string-append dir "/input")))
    (mkdir-p! input) (rpc-dispatch store '(init) "test")
    (cons store input)))
(define (import-text! store dir . extra)
  (safely (lambda () (rpc-dispatch store (append (list 'import-code dir) extra) "test"))))
;; Every alive text file block, as (path lang (src ...)), sorted by path.
(define (text-files store)
  (let ((s (open-and-reduce store)))
    (list-sort (lambda (a b) (string<? (car a) (car b)))
      (map (lambda (id) (list (code-field s id 'path) (code-field s id 'lang)
                              (map (lambda (c) (code-field s c 'src)) (code-children s id))))
           (filter (lambda (id) (eq? 'text (code-field s id 'mode))) (code-files s))))))
(define (block-count store) (length (state-datum (open-and-reduce store))))
(define png-bytes (bytevector 137 80 78 71 13 10 26 10 0 0 255))
(define nul-bytes (string->utf8 "ab\x0;cd\n"))
(define (t1-dir! input)
  (write! (string-append input "/a.sh") (string->utf8 "echo hi\n"))
  (write! (string-append input "/a.sc") (string->utf8 "(define x 1)\n"))
  (write! (string-append input "/Makefile") (string->utf8 "all:\n\techo made\n"))
  (write! (string-append input "/b.png") png-bytes)
  (write! (string-append input "/c.bin") nul-bytes))

;; T1: text is imported, a registered extension or not; the rest is listed.
(let* ((ta (text-area! "t1")) (store (car ta)) (input (cdr ta)))
  (t1-dir! input)
  (let ((a (import-text! store input)))
    (want "T1 a text import keeps a.sh, a.sc and Makefile (bytes as in the files), lists b.png and c.bin as skipped, and holds no block for them"
          (list (answer-head a) (text-files store) (answer-clause a 'skipped))
          (list 'ok
                (list (list "Makefile" #f (list (string->utf8 "all:\n\techo made\n")))
                      (list "a.sc" 'scheme (list (string->utf8 "(define x 1)\n")))
                      (list "a.sh" 'shell (list (string->utf8 "echo hi\n"))))
                '(skipped ("b.png" "c.bin"))))))

;; T2: nothing skipped, no clause; the ok and the imports are asserted first.
(let* ((ta (text-area! "t2")) (store (car ta)) (input (cdr ta)))
  (write! (string-append input "/one.txt") (string->utf8 "one\n"))
  (write! (string-append input "/two.py") (string->utf8 "def two():\n  pass\n"))
  (let ((a (import-text! store input)))
    (want "T2 a directory of text files only answers ok, imports both, and carries no skipped clause"
          (list (answer-head a) (map car (text-files store)) (answer-clause a 'skipped))
          '(ok ("one.txt" "two.py") #f))))

;; T3: a marked projection whose body became binary, imported with
;; --allow-delete: listed, and the file and its children are as they were.
(let* ((ta (text-area! "t3")) (store (car ta)) (input (cdr ta)) (out (string-append root "/t3-out")))
  (write! (string-append input "/x.py") (projection-encode py #f (list (list "new" one) (list "new" two))))
  (import-text! store input)
  (mkdir-p! out)
  (safely (lambda () (rpc-dispatch store (list 'export-code out) "test")))
  (let* ((s (open-and-reduce store))
         (file (find (lambda (id) (equal? (code-field s id 'path) "x.py")) (code-files s)))
         (kids (code-children s file))
         (before (list (map (lambda (id) (list (block-hash s id) (code-field s id 'src))) (cons file kids)) (block-count store)))
         (exported (call-with-port (open-file-input-port (string-append out "/x.py")) get-bytevector-all)))
    (write! (string-append out "/x.py") (bv-append-ff exported))
    (let* ((a (import-text! store out "--allow-delete")) (s2 (open-and-reduce store)))
      (want "T3 a marked projection whose body is no longer text, imported with --allow-delete, is listed as skipped and changes nothing"
            (list (answer-head a) (answer-clause a 'skipped)
                  (equal? before (list (map (lambda (id) (list (block-hash s2 id) (code-field s2 id 'src))) (cons file kids)) (block-count store)))
                  (equal? kids (code-children s2 file)))
            '(ok (skipped ("x.py")) #t #t)))))

;; T1c: a file that opens with a marker-family line and then is not UTF-8 is
;; skipped before any decoding; the valid file beside it is imported.
(let* ((ta (text-area! "t1c")) (store (car ta)) (input (cdr ta)))
  (write! (string-append input "/ok.txt") (string->utf8 "fine\n"))
  (write! (string-append input "/z.txt") (bv-append-ff (string->utf8 "# @file z\n")))
  (let ((a (import-text! store input)))
    (want "T1c a file opening with a marker line and then not UTF-8 is skipped, not refused as projection-invalid, and the valid file is imported"
          (list (answer-head a) (map car (text-files store)) (answer-clause a 'skipped))
          '(ok ("ok.txt") (skipped ("z.txt"))))))

;; T3b: an unmarked file of a path already in the store, now binary, is
;; skipped: no second identity.
(let* ((ta (text-area! "t3b")) (store (car ta)) (input (cdr ta)))
  (write! (string-append input "/u.txt") (string->utf8 "text once\n"))
  (import-text! store input)
  (let ((before (block-count store)))
    (write! (string-append input "/u.txt") (bytevector 255 254 0 97))
    (let ((a (import-text! store input)))
      (want "T3b an unmarked file of a held path, now not text, is skipped and adds no identity"
            (list (answer-head a) (answer-clause a 'skipped) (= before (block-count store)))
            '(ok (skipped ("u.txt")) #t)))))

;; T4 PIN: the datum import over T1's directory reads a.sc and lists the
;; rest, by its own rule.
(let* ((ta (text-area! "t4")) (store (car ta)) (input (cdr ta)))
  (t1-dir! input)
  (write! (string-append input "/a.sc") (string->utf8 "(library (t4 a) (export x) (import (rnrs)) (define x 1))\n"))
  (let ((a (safely (lambda () (rpc-dispatch store (list 'import-code input "--datum") "test")))))
    (want "T4 PIN the datum import of T1's directory reads a.sc and lists Makefile, a.sh, b.png and c.bin as skipped"
          (list (answer-head a) (answer-clause a 'skipped))
          '(ok (skipped ("Makefile" "a.sh" "b.png" "c.bin"))))))

;; T5 PIN: a BOM and CRLF line ends are text.
(let* ((ta (text-area! "t5")) (store (car ta)) (input (cdr ta)))
  (write! (string-append input "/bom.txt") (bv-append (bytevector 239 187 191) (string->utf8 "with a BOM\n")))
  (write! (string-append input "/crlf.txt") (string->utf8 "line one\r\nline two\r\n"))
  (let ((a (import-text! store input)))
    (want "T5 PIN a UTF-8 file with a BOM and a file with CRLF line ends are text and imported"
          (list (answer-head a) (map car (text-files store)) (answer-clause a 'skipped))
          '(ok ("bom.txt" "crlf.txt") #f))))

;; T6 PIN: one file at a time, in the walk's order. An earlier file whose
;; marker header is invalid is refused before a later file is read, as the
;; base did; reading every file first answered the later file's unreadable.
(let* ((ta (text-area! "t6")) (store (car ta)) (input (cdr ta)))
  (write! (string-append input "/a.txt") (string->utf8 "# @file z\n"))
  (write! (string-append input "/b.txt") (string->utf8 "fine\n"))
  (system (string-append "chmod 000 '" input "/b.txt'"))
  (let ((a (import-text! store input)))
    (system (string-append "chmod 644 '" input "/b.txt'"))
    (want "T6 PIN an invalid header in a.txt is refused before an unreadable b.txt is read, as on the base"
          (list (answer-head a) (answer-clause a 'reason))
          '((error projection-invalid) (reason invalid-header)))))
(printf "~a failures\ncode-import complete\n" bad)
(exit (if (zero? bad) 0 1))
