#!r6rs
(import (chezscheme) (theourgia rpc) (theourgia store) (theourgia reduce) (theourgia ffi))
(define bad 0)
(define (want label got expected)
  (if (equal? got expected) (printf "ok ~a\n" label)
      (begin (set! bad (+ bad 1)) (printf "FAIL ~a: ~s WANT ~s\n" label got expected))))
(define root (string-append (or (getenv "THEOURGIA_TEST_ROOT") "/tmp") "/code-datum-" (number->string (get-process-id))))
(mkdir-p! root)
(putenv "THEOURGIA_HOME" (string-append root "/home"))
(define store (string-append root "/store"))
(define input (string-append root "/input"))
(define output (string-append root "/output"))
(mkdir-p! input)
(rpc-dispatch store '(init) "test")
(define (write! path source)
  (call-with-port (open-file-output-port path (file-options no-fail)) (lambda (p) (put-bytevector p (string->utf8 source)))))
(write! (string-append input "/demo.sc")
        "#!chezscheme\n(library (demo)\n (export f x)\n (import (rnrs))\n ;; function docs\n (define (f x) (+ x 1))\n (define x 1/2)\n (define-syntax m (syntax-rules () ((_ x) x)))\n (define-record-type (point make-point point?)\n   (fields (immutable x point-x) (mutable y point-y point-y-set!)))\n (begin (define wrapped 1))\n (mystery unknown 2))\n")
(define result (rpc-dispatch store (list 'import-code input "--datum") "test"))
(want "CD-01 Scheme library imports as datums" (rpc-ok? result) #t)
(define state (open-and-reduce store))
(define (field id key)
  (let* ((b (and id (state-read state id))) (p (and b (assq key (cdr (assq 'fields b)))))) (and p (cdr p))))
(define ids (map cadr (state-datum state)))
(define libs (filter (lambda (id) (eq? 'library (field id 'kind))) ids))
(define codes (filter (lambda (id) (eq? 'code (field id 'kind))) ids))
(want "CD-01 exactly one library wrapper" (length libs) 1)
(want "CD-01 one block per live top-level form" (length codes) 6)
(define ordered (map caddr (filter (lambda (r) (and (pair? libs) (equal? (car r) (car libs)))) (state-outline state))))
(want "CD-01 definition binding sets include every record binding"
      (map (lambda (id) (field id 'names)) ordered)
      '((f) (x) (m) (point make-point point? point-x point-y point-y-set!) () ()))
(want "CD-01 datum body stores structure rather than source text"
      (and (pair? ordered) (field (car ordered) 'body)) '(define (f x) (+ x 1)))
(want "CD-02 adjacent comment belongs to first form doc"
      (and (pair? ordered) (field (car ordered) 'doc)) " ;; function docs\n")
(want "CD-02 form without leading comments has empty doc"
      (and (> (length ordered) 1) (field (cadr ordered) 'doc)) "")
(want "CD-12 library imports are fields" (and (pair? libs) (field (car libs) 'imports)) '((rnrs)))
(want "CD-12 library exports are fields" (and (pair? libs) (field (car libs) 'exports)) '(f x))
(define before (reduce-applied-cut state))
(want "CD-06 datum export succeeds" (rpc-ok? (rpc-dispatch store (list 'export-code output "--datum") "test")) #t)
(want "CD-06 generated file reimports" (rpc-ok? (rpc-dispatch store (list 'import-code output "--datum") "test")) #t)
(want "CD-06 unchanged generated file has zero business events" (reduce-applied-cut (open-and-reduce store)) before)
(printf "~a failures\ncode-datum complete\n" bad)
(exit (if (zero? bad) 0 1))
