#!r6rs
(import (chezscheme) (theourgia rpc) (theourgia ffi) (theourgia trace) (theourgia code-project))
(define bad 0)
(define (want name got expected)
  (if (equal? got expected) (printf "ok ~a\n" name)
      (begin (set! bad (+ bad 1)) (printf "FAIL ~a: ~s WANT ~s\n" name got expected))))
(define root (string-append (or (getenv "THEOURGIA_TEST_ROOT") "/tmp") "/suggest-race-" (number->string (get-process-id))))
(mkdir-p! root)
(putenv "THEOURGIA_HOME" (string-append root "/home"))
(define store (string-append root "/store"))
(rpc-dispatch store '(init) "test")
(define path (string-append root "/input.py"))
(define output (string-append root "/review.py"))
(define original (string->utf8 "def a(): pass\ndef b(): pass\n"))
(define edited (string->utf8 "newer unsent work"))
(define (write! path b)
  (call-with-port (open-file-output-port path (file-options no-fail)) (lambda (p) (put-bytevector p b))))
(define pending "")
(define intercepted #f)
(define port
  (make-custom-textual-output-port "suggestion race"
    (lambda (s start count)
      (set! pending (string-append pending (substring s start (+ start count))))
      (let loop ()
        (let ((end (let scan ((i 0)) (and (< i (string-length pending))
                                         (if (char=? (string-ref pending i) #\newline) i (scan (+ i 1)))))))
          (when end
            (let ((x (read (open-input-string (substring pending 0 end)))))
              (set! pending (substring pending (+ end 1) (string-length pending)))
              (when (and (list? x) (= 4 (length x)) (eq? (cadr x) 'suggest-scanned))
                (set! intercepted #t) (write! path edited))) (loop))))
      count) #f #f (lambda () (values))))
(write! path original)
(define answer
  (parameterize ((current-error-port port))
    (trace-enable! #t)
    (let ((a (rpc-dispatch store (list 'split-suggest path "--output" output) "test")))
      (trace-enable! #f) a)))
(want "CT-20 race reaches scan boundary" intercepted #t)
(want "CT-20 changed input refuses review installation" answer '(error projection-invalid (reason input-changed)))
(want "CT-20 new input bytes survive race" (read-code-bytes path) edited)
(want "CT-20 stale suggestion creates no review destination" (file-exists? output) #f)
(write! path original)
(want "CT-20 unchanged input permits review installation"
      (rpc-ok? (rpc-dispatch store (list 'split-suggest path "--output" output) "test")) #t)
(write! output edited)
(want "CT-20 existing review refuses overwrite"
      (rpc-dispatch store (list 'split-suggest path "--output" output) "test") '(error projection-invalid (reason output-exists)))
(want "CT-20 existing review bytes survive" (read-code-bytes output) edited)
(printf "~a failures\ncode-suggest-race complete\n" bad)
(exit (if (zero? bad) 0 1))
