#!r6rs
(import (chezscheme) (theourgia rpc) (theourgia store) (theourgia reduce) (theourgia ffi)
        (theourgia languages) (theourgia code-project) (theourgia code-markers))
(define bad 0)
(define (want name got expected)
  (if (equal? got expected) (printf "ok ~a\n" name)
      (begin (set! bad (+ bad 1)) (printf "FAIL ~a: ~s WANT ~s\n" name got expected))))
(define root (string-append (or (getenv "THEOURGIA_TEST_ROOT") "/tmp") "/code-suggest-" (number->string (get-process-id))))
(mkdir-p! root)
(putenv "THEOURGIA_HOME" (string-append root "/home"))
(define store (string-append root "/store"))
(rpc-dispatch store '(init) "test")
(define (write! path s)
  (call-with-port (open-file-output-port path (file-options no-fail)) (lambda (p) (put-bytevector p (string->utf8 s)))))
(define counter 0)
(define (result-value a key)
  (let ((p (and (pair? a) (assq key (filter pair? (cdr a))))))
    (and p (cadr p))))
(define (suggest extension input)
  (set! counter (+ counter 1))
  (let ((path (string-append root "/case-" (number->string counter) "." extension)))
    (write! path input)
    (let* ((before (reduce-applied-cut (open-and-reduce store)))
          (a (rpc-dispatch store (list 'split-suggest path) "test")))
      (want "CT-20 suggestion never writes store events" (reduce-applied-cut (open-and-reduce store)) before)
      (want "CT-20 suggestion leaves its original input intact" (read-code-bytes path) (string->utf8 input)) a)))
(define (boundaries a) (result-value a 'boundaries))
(define (byte-count s) (bytevector-length (string->utf8 s)))
(for-each
  (lambda (row)
    (let* ((name (car row)) (ext (cadr row)) (outer (caddr row)) (tail (cadddr row))
           (a (suggest ext (string-append outer tail))))
      (want (string-append "CT-03 " name " nested head stays in outer block") (boundaries a) (list 0 (byte-count outer)))
      (let ((path (result-value a 'working-path)))
        (when path
          (want "CT-20 review copy recovers exact source bytes"
                (apply append (map (lambda (e) (bytevector->u8-list (cadr e)))
                                   (cadr (projection-decode (language-for-path path) (read-code-bytes path)))))
                (bytevector->u8-list (string->utf8 (string-append outer tail))))))))
  '(("javascript" "js" "function outer() {\nfunction inner() {}\n}\n" "function next() {}\n")
    ("python" "py" "class C:\n  def method(self):\n    pass\n" "def next():\n  pass\n")
    ("go" "go" "func outer() {\nfunc inner() {}\n}\n" "func next() {}\n")
    ("rust" "rs" "impl Thing {\nfn inner() {}\n}\n" "fn next() {}\n")
    ("scheme" "ss" "(define (outer)\n(define (inner) 1)\n inner)\n" "(define (next) 2)\n")
    ("markdown" "md" "# Outside\n```scheme\n## Inside\n```\n" "## Next\n")))
(let* ((first "def first():\n  pass\n") (second "# docs\n@decorator\ndef second():\n  pass\n"))
  (want "CT-03 comments and decorators attach to next Python definition"
        (boundaries (suggest "py" (string-append first second))) (list 0 (byte-count first))))
(for-each
  (lambda (row)
    (let* ((a (suggest (car row) (cadr row))))
      (want "CT-04 ambiguous or unbalanced syntax falls back to whole file" (boundaries a) '(0))
      (want "CT-04 fallback carries an explicit warning" (pair? (result-value a 'warnings)) #t)))
  '(("js" "function a() {\nfunction b() {}\n")
    ("js" "function a() { return /x/; }\nfunction b() {}\n")
    ("js" "function a() { return `x`; }\nfunction b() {}\n")
    ("py" "def a():\n  x = \"unterminated\ndef b():\n  pass\n")
    ("ss" "(define a #;ignored 1)\n(define b 2)\n")
    ("md" "# A\n```\n## B\n")
    ("sh" "a() { cat <<END; }\nb() { :; }\n")))
(let* ((first "def a():\n  x = \"\"\"\ndef fake():\n  pass\n\"\"\"\n") (next "def b():\n  pass\n"))
  (want "CT-03 triple-quoted Python string hides definition text"
        (boundaries (suggest "py" (string-append first next))) (list 0 (byte-count first))))
(let* ((first "func a() { x := `\nfunc fake() {}\n` }\n") (next "func b() {}\n"))
  (want "CT-03 raw Go string hides definition text"
        (boundaries (suggest "go" (string-append first next))) (list 0 (byte-count first))))
(let* ((first "function a() { /* }\nfunction fake() {}\n*/ return \"}\"; }\n") (next "function b() {}\n"))
  (want "CT-03 comments and quotes suspend delimiter counting"
        (boundaries (suggest "js" (string-append first next))) (list 0 (byte-count first))))
(want "CT-02 unknown language remains one block" (boundaries (suggest "toy" "thing First {}\nthing Second {}\n")) '(0))
(register-language! '((lang "toy") (extensions ("toy")) (line-comment "//")
                      (def-heads ("^thing ([A-Za-z]+)")) (name-capture 1)
                      (suggest-only ((top-level "brace") (pairs ("{}")) (quote-delimiters ("\""))
                                     (uncertain-tokens ()) (prefix-lines ())))))
(want "CT-02 registered data row activates existing profile"
      (boundaries (suggest "toy" "thing First {}\nthing Second {}\n")) '(0 15))
(printf "~a failures\ncode-suggest1 complete\n" bad)
(exit (if (zero? bad) 0 1))
