#!r6rs
(import (chezscheme) (theourgia text-code))
(define bad 0)
(define (want label got expected)
  (if (equal? got expected) (printf "ok ~a\n" label)
      (begin (set! bad (+ bad 1)) (printf "FAIL ~a: ~s WANT ~s\n" label got expected))))
(define (forms path) (call-with-input-file path read))
(define numeric-sites '())
(define language-sites '())
(define language-names '("scheme" "javascript" "typescript" "python" "go" "rust" "c" "java" "shell" "markdown"))
(define (walk-numeric x file)
  (when (pair? x)
    (unless (eq? 'quote (car x))
      (when (memq (car x) '(read get-datum string->number eval load)) (set! numeric-sites (cons (list file x) numeric-sites)))
      (walk-numeric (car x) file)
      (walk-numeric (cdr x) file))))
(define (contains-language? x)
  (cond ((string? x) (and (member x language-names) #t))
        ((pair? x) (or (contains-language? (car x)) (contains-language? (cdr x)))) (else #f)))
(define (walk-branches x file)
  (when (pair? x)
    (when (and (memq (car x) '(string=? equal? eq? eqv? case)) (contains-language? x))
      (set! language-sites (cons (list file x) language-sites)))
    (unless (eq? 'quote (car x))
      (walk-branches (car x) file)
      (walk-branches (cdr x) file))))
(for-each (lambda (file) (walk-numeric (forms file) file)) '("text-code.ss" "regex.ss" "languages.ss"))
(for-each (lambda (file) (walk-branches (forms file) file)) '("text-code.ss" "code-project.ss" "code-suggest.ss"))
(want "CT-14 source inventory excludes numeric readers from name extraction" numeric-sites '())
(want "CT-02 shared engines have no language-name branch" language-sites '())
(printf "~a failures\ncode-text-audit complete\n" bad)
(exit (if (zero? bad) 0 1))
