#!r6rs
(import (chezscheme) (theourgia md) (theourgia project)
        (theourgia store) (theourgia reduce) (theourgia ffi))

(define bad 0)
(define (want label got expected)
  (if (equal? got expected) (printf "ok ~a\n" label)
      (begin (set! bad (+ bad 1))
             (printf "FAIL ~a: ~s WANT ~s\n" label got expected))))
(define root (string-append (or (getenv "THEOURGIA_TEST_ROOT") "/tmp")
                            "/crlf-" (number->string (get-process-id))))
(when (file-exists? root) (error 'crlf "Use a fresh root" root))
(mkdir-p! root)
(putenv "THEOURGIA_HOME" (string-append root "/home"))
(define (put! path text)
  (call-with-port (open-file-output-port path (file-options no-fail))
    (lambda (p) (put-bytevector p (string->utf8 text)))))
(define (get path)
  (call-with-port (open-file-input-port path) get-bytevector-all))
(define (ranges text)
  (let ((d (md-split text)))
    (list (doc-front d) (doc-src d)
          (map (lambda (s) (list (section-level s) (section-title s)
                                (section-heading-src s) (section-src s)))
               (doc-sections d)))))
(define (field b key) (let ((p (assq key (cdr (assq 'fields b))))) (and p (cdr p))))
(define (exercise label nl)
  (let* ((text (string-append "# Alpha" nl nl "first body" nl nl
                              "## Beta" nl nl "second body" nl))
         (dir (string-append root "/" label))
         (src (string-append dir "/src")) (out (string-append dir "/out"))
         (marked (string-append dir "/marked")) (store (string-append dir "/store")))
    (for-each mkdir-p! (list src out marked))
    (store-init! store)
    (put! (string-append src "/doc.md") text)
    (want (string-append "QR-02 " label " exact ranges") (ranges text)
          (list "" "" (list (list 1 "Alpha" (string-append "# Alpha" nl)
                                  (string-append nl "first body" nl nl))
                            (list 2 "Beta" (string-append "## Beta" nl)
                                  (string-append nl "second body" nl)))))
    (want (string-append "QR-01 " label " import succeeds")
          (for-all (lambda (a) (eq? 'ok (car a))) (import-md store src "test")) #t)
    (let* ((state (open-and-reduce store))
           (rows (state-outline state))
           (name (lambda (id)
                   (if (equal? id 'root) 'root
                       (let ((b (state-read state id)))
                         (if (eq? 'doc (field b 'kind)) 'file (field b 'title)))))))
      (want (string-append "QR-01 " label " outline has file Alpha Beta") (length rows) 3)
      (want (string-append "QR-01 " label " parent relationships")
            (sort (lambda (a b) (string<? (format "~s" a) (format "~s" b)))
                  (map (lambda (r) (list (name (car r)) (name (caddr r)))) rows))
            '(("Alpha" "Beta") (file "Alpha") (root file)))
      (export-md store out)
      (want (string-append "QR-02 " label " export preserves bytes")
            (get (string-append out "/doc.md")) (string->utf8 text))
      (export-md store marked #t)
      (let ((before (reduce-applied-cut state)))
        (import-md store marked "test")
        (want (string-append "QR-05 " label " marker import adds no events")
              (reduce-applied-cut (open-and-reduce store)) before))
      (export-md store out)
      (want (string-append "QR-05 " label " marker roundtrip preserves bytes")
            (get (string-append out "/doc.md")) (string->utf8 text)))))
(exercise "crlf" "\r\n")
(exercise "lf" "\n")
(want "QR-03 mixed newlines exact ranges"
      (ranges "# Alpha\r\nbody\n## Beta\nend")
      '("" "" ((1 "Alpha" "# Alpha\r\n" "body\n") (2 "Beta" "## Beta\n" "end"))))
(want "QR-03 reverse mixed newlines exact ranges"
      (ranges "# Alpha\nbody\r\n## Beta\r\nend")
      '("" "" ((1 "Alpha" "# Alpha\n" "body\r\n") (2 "Beta" "## Beta\r\n" "end"))))
(printf "~a failures\ncrlf complete\n" bad)
(exit (if (zero? bad) 0 1))
