#!r6rs
(import (chezscheme) (theourgia datum-code) (theourgia source-lex) (theourgia ffi))
(define bad 0)
(define (want label got expected)
  (if (equal? got expected) (printf "ok ~a\n" label)
      (begin (set! bad (+ bad 1)) (printf "FAIL ~a: ~s WANT ~s\n" label got expected))))
(define (parse s) (datum-source-read (string->utf8 s)))
(define names
  '(((define x 1) (x)) ((define (f x) x) (f)) ((define-syntax m 1) (m))
    ((define-record-type (point make-point point?) (fields (immutable x get-x) (mutable y get-y set-y!)))
     (point make-point point? get-x get-y set-y!))
    ((define-record-type point (fields x (mutable y))) (point make-point point? point-x point-y point-y-set!))
    ((begin (define wrapped 1)) ()) ((unknown thing 1) ())))
(for-each (lambda (row) (want "CD-01 complete binding set" (datum-names (car row)) (cadr row))) names)
(let ((forms (parse ";; docs\n(define (f x) ; inside\n x)\n#;(define ignored 1)\n(define x 1/2)")))
  (want "CD-02 adjacent comments attach without moving body data" (cadar forms) ";; docs\n")
  (want "CD-02 internal comment reports independently counted coordinates"
        (list-ref (car forms) 5) '((warning internal-comment (byte-offset 22) (line 2) (column 15))))
  (want "CD-03 discarded definition creates no ghost block" (map car forms) '((define (f x) x) (define x 1/2)))
  (want "CD-02 no leading comment means empty doc" (cadr (cadr forms)) ""))
(want "CD-02 blank line breaks doc attachment" (cadar (parse ";; not attached\n\n(define x 1)")) "")
(let ((forms (parse "(define x \"; #; #|\")\n#| outer #| nested |# end |#\n(define y #;(discard ; ghost\n  1) 2)")))
  (want "CD-03 strings and reader comments retain reader semantics" (map car forms) '((define x "; #; #|") (define y 2)))
  (want "CD-03 discarded/internal string text produces no comment warnings" (map (lambda (f) (list-ref f 5)) forms) '(() ())))
(want "CD-04 Chez fold-case directive applies to all nested symbols"
      (map car (parse "#!fold-case\n(define MiXeD (quote #(A B)))")) '((define mixed '#(a b))))
(want "CD-04 no-fold-case control retains spelling"
      (map car (parse "#!no-fold-case\n(define MiXeD (quote #(A B)))")) '((define MiXeD '#(A B))))
(define entered 0)
(for-each
  (lambda (source)
    (set! entered 0)
    ;; The real reader adapter stops here if a mutation bypasses admission.
    ;; This prevents the dangerous token from ever allocating a large number.
    (source-reader-observer! (lambda (text position) (set! entered (+ entered 1)) (raise 'probe-stopped)))
    (let ((a (guard (e (#t e)) (parse source) 'accepted)))
      (want "CD-19 unsafe source is refused" (and (pair? a) (eq? (car a) 'error)) #t)
      (want "CD-19 dangerous token reaches reader zero times" entered 0)))
  (append '("#e1e99999999" "#; #e1e99999999" "#E#d+1L+99999999" "#D#E-1s-99999999"
            "(define safe 1)\n(define danger #e1d99999999)" "#1000000000(1)" "#1=(a . #1#)")
          (list (make-string 300 #\9))))
(source-reader-observer! (lambda (text position) (set! entered (+ entered 1))))
(set! entered 0)
(want "CD-19 legal numeric twin reaches the real reader" (map car (parse "#e1e3 1/2 1.5 #e#xeeee")) '(1000 1/2 1.5 61166))
(want "CD-19 legal numeric twin has reader observations" (> entered 0) #t)
(want "CD-19 dangerous-looking string is legal data" (map car (parse "\"#e1e99999999\"")) '("#e1e99999999"))
(source-reader-observer! #f)
(for-each
  (lambda (source)
    (set! entered 0)
    (source-reader-observer! (lambda args (set! entered (+ entered 1)) (raise 'probe-stopped)))
    (want "CD-19 prefix resource limit answers before reader"
          (guard (e (#t (and (pair? e) (equal? (assq 'reason (filter pair? e)) '(reason prefix-limit))))) (parse source) #f) #t)
    (want "CD-19 prefix resource limit has zero reader entries" entered 0))
  (list (string-append (make-string 257 #\') "x")
        (string-append (apply string-append (make-list 257 "#; ")) "x")))
(source-reader-observer! #f)
(want "CD-02 lone CR doc remains attached" (cadar (parse ";; CR doc\r(define x 1)")) ";; CR doc\r")
(define golden
  (list
    (cons "(define x 1)" "(define x 1)\n")
    (cons "(define (f x) (+ x 1))" "(define (f x) (+ x 1))\n")
    (cons "(quote x)" "'x\n")
    (cons "(a . b)" "(a . b)\n")
    (cons "#\\space" "#\\space\n")
    (cons "|weird sym|" "weird\\x20;sym\n")
    (cons "#(1 2)" "#(1 2)\n")
    (cons "#vu8(0 255)" "#vu8(0 255)\n")
    (cons "\"a\\n\\\"b\\\\c\"" "\"a\\n\\\"b\\\\c\"\n")
    (cons "1/2" "1/2\n")
    (cons "1.5" "1.5\n")
    (cons "-0.0" "-0.0\n")
    (cons "(define (many alpha beta gamma delta epsilon zeta eta theta iota kappa lambda mu) (list alpha beta gamma delta epsilon zeta eta theta iota kappa lambda mu))" "(define (many alpha beta gamma delta epsilon zeta eta theta iota kappa\n         lambda mu)\n   (list alpha beta gamma delta epsilon zeta eta theta iota kappa lambda\n         mu))\n")
))
(for-each
  (lambda (row)
    (let ((datum (caar (parse (car row)))))
      (want "CD-06 fixed P1 output matches independent Chez reference" (datum-print datum) (cdr row))
      (parameterize ((pretty-line-length 12) (pretty-one-line-limit 4) (print-radix 16) (print-length 1) (print-level 1))
        (want "CD-06 caller print defaults cannot change output" (datum-print datum) (cdr row))))) golden)
(printf "~a failures\ndatum-reader complete\n" bad)
(exit (if (zero? bad) 0 1))
