#!r6rs
(import (chezscheme) (theourgia store) (theourgia reduce) (theourgia rpc) (theourgia ffi)
        (theourgia code-project) (theourgia code-markers) (theourgia languages) (theourgia wire) (theourgia log))
(define bad 0)
(define (want label got expected)
  (if (equal? got expected) (printf "ok ~a\n" label)
      (begin (set! bad (+ bad 1)) (printf "FAIL ~a: ~s WANT ~s\n" label got expected))))
(define root (string-append (or (getenv "THEOURGIA_TEST_ROOT") "/tmp") "/datum-meta-" (number->string (get-process-id))))
(mkdir-p! root)
(putenv "THEOURGIA_HOME" (string-append root "/home"))
(define store (string-append root "/store"))
(rpc-dispatch store '(init) "test")
(define marker ";; @block writer.1\n")
(define before (reduce-applied-cut (open-and-reduce store)))
(define put (with-store-write store (lambda (s v) (list (list 'insert 'root #f (list '(kind . code) '(mode . datum) '(body define x 1) (cons 'doc marker))))) "test"))
(want "CD-08 put refuses a recovery marker in doc" (and (pair? put) (eq? (caar put) 'error)) #t)
(want "CD-08 refused put leaves authoritative cut unchanged" (reduce-applied-cut (open-and-reduce store)) before)
(with-store-write store (lambda (s v) (list '(insert root #f ((kind . code) (mode . datum) (body define x 1) (doc . ";; old\n"))))) "test")
(define id (cadar (state-datum (open-and-reduce store))))
(set! before (reduce-applied-cut (open-and-reduce store)))
(want "CD-08 set refuses a recovery marker in doc" (rpc-ok? (rpc-dispatch store (list 'set id "doc" marker) "test")) #f)
(want "CD-08 refused set leaves authoritative cut unchanged" (reduce-applied-cut (open-and-reduce store)) before)
(want "CD-08 nonmarker suffix control remains writable"
      (rpc-ok? (rpc-dispatch store (list 'set id "doc" ";; @block writer.1 trailing prose\n") "test")) #t)
(define r (reduce-empty))
(reduce-apply! r "remote" 1 '() (list 'put (list '(kind . code) '(mode . datum) '(body define x 1) (cons 'doc marker))))
(want "CD-08 replay never materializes a marker-bearing doc" (state-read r (block-id "remote" 1)) #f)
(want "CD-08 replay reports malformed record with its event and reason" (reduce-noted r)
      '((malformed-record (event "remote" 1) (reason marker-in-doc))))
(want "CD-12 direct body update succeeds" (rpc-ok? (rpc-dispatch store (list 'set id "body" "(define renamed #\\space)") "test")) #t)
(let ((state (open-and-reduce store)))
  (want "CD-12 direct body update changes derived primary name" (code-field state id 'name) 'renamed)
  (want "CD-12 direct body update changes complete binding set" (code-field state id 'names) '(renamed))
  (want "CD-05 character body survives source/storage boundary" (code-field state id 'body) '(define renamed #\space))
  (want "CD-05 character data has a usable block hash" (guard (e (#t #f)) (string? (block-hash state id))) #t))
(want "CD-12 derived names cannot be overwritten independently"
      (cadr (rpc-dispatch store (list 'set id "name" "wrong") "test")) 'derived-field)
(define entered 0)
(source-reader-observer! (lambda (text position) (set! entered (+ entered 1)) (raise 'probe-stopped)))
(want "CD-19 set body refuses dangerous source before reading"
      (rpc-dispatch store (list 'set id "body" "#; #e1e99999999 (define safe 1)") "test")
      '(error bad-source (reason unsafe-numeric-token) (character-offset 3)))
(want "CD-19 set body dangerous token reaches reader zero times" entered 0)
(source-reader-observer! #f)
(with-store-write store (lambda (s v) (list (list 'set id 'body (string->symbol "weird sym")))) "test")
(want "CD-05 arbitrary Scheme symbol has a usable block hash"
      (guard (e (#t #f)) (string? (block-hash (open-and-reduce store) id))) #t)
(define replay-store (string-append root "/replay-store"))
(rpc-dispatch replay-store '(init) "test")
(define session (log-begin replay-store (lambda args 'applied)))
(define view (session-view session))
(define replay-id (block-id (view-writer view) (view-expect-seq view)))
(session-append! session (make-frame (view-revision view) (view-epoch view) (view-writer view)
                                    (view-expect-seq view) "independent-fixture" '()
                                    (list 'put (list '(kind . code) '(mode . datum) '(body define bad 1) (cons 'doc marker)))))
(session-commit! session)
(log-end! session)
(let* ((state (open-and-reduce replay-store)) (check (store-check replay-store)))
  (want "CD-08 independent physical log cannot materialize invalid doc" (state-read state replay-id) #f)
  (want "CD-08 independent physical log retains its integrity diagnostic"
        (reduce-noted state) (list (list 'malformed-record (list 'event (view-writer view) (view-expect-seq view)) '(reason marker-in-doc))))
  (want "CD-08 check reports physical malformed history as damaged" (cadr (assq 'verdict (cdr check))) 'damaged))
(for-each
  (lambda (doc)
    (let* ((before (reduce-applied-cut (open-and-reduce store)))
           (result (with-store-write store (lambda (s v) (list (list 'set id 'doc doc))) "test")))
      (want "CD-08 malformed doc is refused before append" (and (pair? result) (eq? (caar result) 'error)) #t)
      (want "CD-08 malformed doc leaves cut unchanged" (reduce-applied-cut (open-and-reduce store)) before)))
  (list "(define injected 1)\n" ";; unterminated" ";; separated\n\n" 7 '#vu8(59 10)))
(want "CD-08 terminated CR comment doc remains writable"
      (rpc-ok? (rpc-dispatch store (list 'set id "doc" "  ;; valid\r") "test")) #t)
(printf "~a failures\ndatum-metadata1 complete\n" bad)
(exit (if (zero? bad) 0 1))
