#!r6rs
(import (chezscheme) (theourgia rpc) (theourgia store) (theourgia request)
        (theourgia ffi) (theourgia trace) (theourgia log) (theourgia wire)
        (theourgia digest))
(define bad 0)
(define (want label got expected)
  (if (equal? got expected) (printf "ok ~a\n" label)
      (begin (set! bad (+ bad 1)) (printf "FAIL ~a: ~s WANT ~s\n" label got expected))))
(define root (string-append (or (getenv "THEOURGIA_TEST_ROOT") "/tmp")
                            "/evidence-index-" (number->string (get-process-id))))
(when (file-exists? root) (error 'evidence-index "Use a fresh root" root))
(mkdir-p! root)
(define store (string-append root "/store"))
(putenv "THEOURGIA_HOME" (string-append store "-home"))
(define init (rpc-dispatch store '(init) "test"))
(define writer (cadr (assq 'writer (cdr init))))
(with-store-write store (lambda (state view)
                         (map (lambda (n) (list 'insert 'root #f (list (cons 'title (number->string n))))) (iota 40))) "test")
(rpc-dispatch store (list 'insert "--title" "target" "--req" "indexed" "--cursor" (string-append writer ":40")) "test")
(define identity (cons writer "indexed"))
(define (query) (store-evidence store identity))
(want "QI-01 indexed identity is present" (length (query)) 1)
(define out (open-output-string))
(parameterize ((current-error-port out)) (trace-enable! #t) (query) (trace-enable! #f))
(define probes
  (let ((p (open-input-string (get-output-string out))))
    (let loop ((n 0)) (let ((x (read p)))
      (if (eof-object? x) n
          (loop (+ n (if (and (pair? x) (eq? 'trace (car x)) (eq? 'identity-source-decode (cadr x))) 1 0))))))))
(want "QI-07 hot disk query decodes only the matching frame" probes 1)
(define checkpoint (string-append store "/request-index.sexp"))
(want "QI-06 readonly evidence lookup does not write a cache" (file-exists? checkpoint) #f)
(define dir (writer-directory store writer))
(define segment (string-append dir "/000001.sexp"))
(define original (call-with-port (open-file-input-port segment) get-bytevector-all))
(define frame
  (let loop ((i (- (bytevector-length original) 2)))
    (if (or (< i 0) (= (bytevector-u8-ref original i) 10))
        (let ((b (make-bytevector (- (bytevector-length original) (+ i 1)))))
          (bytevector-copy! original (+ i 1) b 0 (bytevector-length b)) b)
        (loop (- i 1)))))
(define incoming (string-append dir "/incoming"))
(mkdir-p! incoming)
(define candidate (string-append incoming "/candidate"))
(call-with-port (open-file-output-port candidate) (lambda (p) (put-bytevector p frame)))
(want "QI-03 newly arrived incoming evidence invalidates a hot index"
      (list-sort (lambda (a b) (string<? (symbol->string a) (symbol->string b))) (map ev-placement (query)))
      '(incoming valid-history))
(delete-file candidate)
(want "QI-03 clearing a duplicate location preserves the verified original"
      (map ev-placement (query)) '(valid-history))
(define manifest (string-append dir "/published.sexp"))
(call-with-output-file manifest (lambda (p) (write '() p)))
(want "QI-05 unchanged sequences with a new manifest become unlisted" (map ev-placement (query)) '(unlisted))
(delete-file manifest)
(want "QI-05 restored metadata restores verifiable placement" (map ev-placement (query)) '(valid-history))
(store-snapshot! store "test")
(want "QI-09 snapshot persists a derived identity checkpoint" (file-exists? checkpoint) #t)
(define (child . req)
  (let ((report (string-append root "/child.sexp")))
    (let ((code (system (string-append "scheme --script test/evidence-index-child.ss " store " " writer " " report
                                     (if (null? req) "" (string-append " " (car req)))))))
      (if (and (= code 0) (file-exists? report)) (call-with-input-file report read) (list 'child-failed code)))))
(want "QI-06 a fresh process reconstructs the same identity" (child) '(valid-history))
(define checkpoint-bytes (and (file-exists? checkpoint) (call-with-port (open-file-input-port checkpoint) get-bytevector-all)))
(when checkpoint-bytes
  ;; A syntactically valid, checksummed cache still cannot invent log evidence.
  (let* ((x (storable-decode (string->sexpr-extended (utf8->string checkpoint-bytes))))
         (body (list-ref x 4)) (decoded (decode-line frame)) (a (cadddr decoded))
         (fake (encode-record (cadr decoded) (caddr decoded)
                              (cons (car a) (cons (cons writer "forged") (cddr a)))
                              (list-ref decoded 4) (list-ref decoded 5)))
         (entries (map (lambda (e)
                         (if (equal? (cadddr e) frame)
                             (list (car e) (cadr e) (caddr e) fake (list-ref e 4)) e)) (cadr body)))
         (new-body (list (car body) entries))
         (encoded (string->utf8 (sexpr->string-extended (storable-encode new-body))))
         (forged (list 'request-index 1 (caddr x) (bytevector->hex (sha256 encoded)) new-body)))
    (call-with-port (open-file-output-port checkpoint (file-options no-fail))
      (lambda (p) (put-bytevector p (string->utf8 (sexpr->string-extended (storable-encode forged))))))
    (want "QI-04 cached frame bytes cannot manufacture verified evidence"
          (child "forged") '(index-evidence-missing))
    (delete-file checkpoint)
    (want "QI-06 a forged cache key is not a permanent execution fence" (child "forged") '())))
(when checkpoint-bytes
  (call-with-output-file checkpoint (lambda (p) (display "(broken" p)) 'replace))
(want "QI-06 a corrupt checkpoint falls back to real records" (child) '(valid-history))
(when checkpoint-bytes
  (call-with-port (open-file-output-port checkpoint (file-options no-fail)) (lambda (p) (put-bytevector p checkpoint-bytes))))
;; The old checkpoint is a missing-evidence hint, never proof of execution.
(delete-file segment)
(want "QI-04 a checkpoint without the source refuses to forget a seen identity"
      (child) '(index-evidence-missing))
(printf "~a failures\nevidence-index complete\n" bad)
(exit (if (zero? bad) 0 1))
