#!chezscheme
;; The faults that leave a file behind, so the file can be asked what
;; actually happened rather than the error being taken at its word.
(import (chezscheme) (theourgia ffi))
(define dir (cadr (command-line)))
(system (string-append "rm -rf " dir "; mkdir -p " dir "/reg"))
(define log (string-append dir "/000001.sexp"))
(define reg (string-append dir "/reg/instances.sexp"))
(define line (string->utf8 "0123456789abcdefghijklmnopqrstuvwxyz\n"))
(define fd (fd-open log '(read-write create append)))
(define rfd (fd-open reg '(read-write create append)))
(parameterize ((theourgia-trace? #t))
  (guard (e ((fs-error? e)
             (printf "write raised op=~a errno=~a\n" (fs-error-op e) (fs-error-errno e))))
    (printf "write-all! -> ~a\n" (write-all! fd line)))
  (guard (e ((fs-error? e)
             (printf "fsync(log) raised op=~a errno=~a\n" (fs-error-op e) (fs-error-errno e))))
    (fsync! fd)
    (printf "fsync(log) returned\n"))
  (guard (e ((fs-error? e)
             (printf "fsync(registry) raised op=~a errno=~a\n" (fs-error-op e) (fs-error-errno e))))
    (fsync! rfd)
    (printf "fsync(registry) returned\n")))
(fd-close fd) (fd-close rfd)
(printf "log holds ~a of ~a bytes\n" (file-size log) (bytevector-length line))
