#!r6rs
(import (chezscheme) (theourgia reduce) (theourgia request) (theourgia trace))
(define bad 0)
(define (want label got expected)
  (if (equal? got expected) (printf "ok ~a\n" label)
      (begin (set! bad (+ bad 1)) (printf "FAIL ~a: ~s WANT ~s\n" label got expected))))
(define (writer n) (format "w~7,'0d" n))
(define (payload title) (list 'put (list (cons 'kind 'section) (cons 'title title) '(parent . root) '(ord . 1))))
(define (actor origin req) (list "test" (cons origin req) 'single "fp" #f (cons origin 0)))
(define (put r n origin req)
  (reduce-apply! r (writer n) 1 '() (payload req) (actor origin req)))
(define r (reduce-empty))
(do ((n 1 (+ n 1))) ((> n 128)) (put r n "origin00" (number->string n)))
(define out (open-output-string))
(parameterize ((current-error-port out))
  (trace-enable! #t)
  (put r 129 "origin00" "129")
  (trace-enable! #f))
(define probes
  (let ((p (open-input-string (get-output-string out))))
    (let loop ((n 0))
      (let ((x (read p)))
        (if (eof-object? x) n
            (loop (+ n (if (and (pair? x) (equal? '(trace identity-probe) (list (car x) (cadr x)))) 1 0))))))))
(want "QI-07 a new independent identity visits one bucket member" probes 1)
(want "QI-01 independent request IDs remain visible" (length (state-datum r)) 129)
(put r 130 "other000" "129")
(want "QI-01 equal request strings with different origins stay independent" (length (state-datum r)) 130)
(define restored (rows->state (state->rows r)))
(put r 131 "origin00" "129")
(put restored 131 "origin00" "129")
(want "QI-02 both duplicate single claims are excluded" (length (state-datum r)) 129)
(want "QI-08 snapshot restore retains revocation evidence" (state-hash restored) (state-hash r))
(want "QI-02 both events carry a conflict gate"
      (map (lambda (w) (let ((p (assoc (cons (writer w) 1) (reduce-gates r)))) (and p (cdr p)))) '(129 131))
      '(plan-conflict plan-conflict))
(want "QI-08 unrelated origin is not revoked" (and (state-read r (block-id (writer 130) 1)) #t) #t)

;; Ordinary causal arrivals must wake the dependent identity as well.
(define s (reduce-empty))
(define origin "plan0000")
(define key (cons origin "p"))
(define after (cons origin 0))
(define intent '(insert root #f ((kind . section) (title . "child"))))
(define plan (list 'plan "p" "fp" after (list (cons 0 intent))))
(reduce-apply! s origin 1 '(("base0000" . 1)) plan (list "test" key 'plan "fp" #f after))
(reduce-apply! s origin 2 '() (payload "child") (list "test" key 0 "fp" (cons origin 1) after))
(want "QI-08 causal missing plan remains pending" (length (state-datum s)) 0)
(reduce-apply! s "base0000" 1 '() (payload "base") "ordinary")
(want "QI-08 an ordinary arrival wakes the plan and member" (length (state-datum s)) 2)
(want "QI-08 completed causal closure has no gates" (reduce-gates s) '())
(printf "~a failures\nidentity-index complete\n" bad)
(exit (if (zero? bad) 0 1))
