#!r6rs
(import (chezscheme) (theourgia log) (theourgia ffi) (theourgia digest))
;; Capture actual content versions at the product's synchronous trace seam.
;; This observer performs no product recovery, flush or namespace operation.
(define args (command-line-arguments))
(define root (car args))
(define report (open-output-file (cadr args) 'replace))
(define (json x p)
  (cond ((string? x)
         (display #\" p)
         (string-for-each (lambda (c)
                           (case c ((#\" #\\) (display #\\ p) (display c p))
                                 ((#\newline) (display "\\n" p))
                                 ((#\return) (display "\\r" p))
                                 ((#\tab) (display "\\t" p))
                                 (else (display c p)))) x)
         (display #\" p))
        ((number? x) (display x p))
        ((list? x) (display "[" p)
         (let loop ((xs x))
           (unless (null? xs) (json (car xs) p)
                   (unless (null? (cdr xs)) (display "," p)) (loop (cdr xs))))
         (display "]" p))
        (else (error 'json "Unsupported observation" x))))
(define (snapshot)
  (let walk ((path root) (relative "."))
    (let-values (((device inode) (path-device-inode path)))
      (let ((dir? (file-directory? path)))
        (cons (list relative (if dir? "dir" "file")
                    (format "~a:~a" device inode)
                    (if dir? "" (bytevector->hex
                                  (call-with-port (open-file-input-port path)
                                    (lambda (p) (let ((b (get-bytevector-all p)))
                                                  (if (eof-object? b) #vu8() b)))))))
              (if dir? (apply append (map (lambda (name)
                                           (walk (string-append path "/" name)
                                                 (if (string=? relative ".") name
                                                     (string-append relative "/" name))))
                                         (list-sort string<? (directory-list path)))) '()))))))
(define (emit op subjects)
  (json (list op subjects (snapshot)) report) (newline report) (flush-output-port report))
(define pending "")
(define observer-failed #f)
(define (path-text x) (if (symbol? x) (symbol->string x) x))
(define (line! line)
  (guard (e (#t (set! observer-failed #t)))
    (let ((x (read (open-input-string line))))
      (when (and (list? x) (= (length x) 4) (eq? 'trace (car x)))
        (let* ((subject (caddr x))
               (paths (if (pair? subject) (list (path-text (car subject)) (path-text (cdr subject)))
                          (list (path-text subject)))))
          (when (for-all (lambda (p) (and (string? p) (>= (string-length p) (string-length root))
                                          (string=? root (substring p 0 (string-length root))))) paths)
            (emit (symbol->string (cadr x))
                  (map (lambda (p) (if (string=? p root) "." (substring p (+ 1 (string-length root)) (string-length p)))) paths))))))))
(define port
  (make-custom-textual-output-port "model observer"
    (lambda (s start count)
      (set! pending (string-append pending (substring s start (+ start count))))
      (let loop ()
        (let ((end (let search ((i 0))
                     (cond ((= i (string-length pending)) #f)
                           ((char=? (string-ref pending i) #\newline) i)
                           (else (search (+ i 1)))))))
          (when end (let ((line (substring pending 0 end)))
                      (set! pending (substring pending (+ end 1) (string-length pending)))
                      (line! line)) (loop))))
      count) #f #f (lambda () (values))))
(emit "initial" '())
(parameterize ((current-error-port port))
  (trace-enable! #t)
  (for-each (lambda (entry)
              (emit "begin" (list (car entry) (bytevector->hex (string->utf8 (cadr entry)))))
              (atomic-write! (string-append root "/" (car entry)) (string->utf8 (cadr entry)) 'working)
              (emit "ack" (list (car entry))))
            (if (and (> (length args) 2) (string=? (caddr args) "recover"))
                '(("a/1" "done"))
                '(("a/1" "new1") ("b/1" "new2") ("a/2" "new3"))))
  (trace-enable! #f))
(close-port report)
(when observer-failed (error 'model-trace "NO-READING: observation failed"))
(printf "model-trace complete\n")
