#!r6rs
(import (chezscheme) (theourgia store) (theourgia reduce) (theourgia log)
        (theourgia request) (theourgia wire) (theourgia rpc) (theourgia arguments))
(define failures 0)
(define (check name value)
  (unless value (set! failures (+ failures 1)))
  (display (if value "PASS " "FAIL ")) (display name) (newline))
(define root (string-append "/tmp/theourgia-q8-" (number->string (get-process-id))))
(mkdir root)
(mkdir (string-append root "/machine"))
(putenv "THEOURGIA_HOME" (string-append root "/machine"))
(define w "mirrorzz")
(define v "otherzzz")
(define after (cons w 0))
(define identity (cons w "plan-one"))
(define fp (request-fingerprint "review" 'insert '("wanted") after))
(define (actor sub pe) (list "review" identity sub fp pe after))
(define (put title) (list 'put (list (cons 'kind 'section) (cons 'title title) '(parent . root) '(ord . 0))))
(define intent '(insert root #f ((kind . section) (title . "Wanted"))))
(define plan (list 'plan "plan-one" fp after (list (cons 0 intent))))
(define p (list w 1 '() plan (actor 'plan #f)))
(define a (list w 2 '() (put "Wanted") (actor 0 (cons w 1))))
(define b (list v 1 (list (cons w 1)) (put "Wanted") (actor 0 (cons w 1))))
(define dependent (list "childzzz" 1 (list (cons w 2)) (put "Dependent") "review"))
(define (feed r record) (apply reduce-apply! r record))
(define (reduce-records records)
  (let ((r (reduce-empty))) (for-each (lambda (x) (feed r x)) records) r))
(define (visible? r writer seq) (and (state-read r (block-id writer seq)) #t))
(define good (reduce-records (list p a)))
(check 'valid-plan-member-applied (visible? good w 2))
(define wrong (list w 2 '() (put "Wrong") (actor 0 (cons w 1))))
(define bad (reduce-records (list p wrong)))
(check 'mismatched-member-excluded (not (visible? bad w 2)))
(check 'mismatch-noted (assq 'plan-mismatch (reduce-noted bad)))
(define pending (reduce-records (list a)))
(check 'member-without-plan-pending (not (visible? pending w 2)))
(feed pending p)
(check 'late-plan-releases-member (visible? pending w 2))
(define final-hash #f)
(for-each
 (lambda (rs)
   (let ((r (reduce-records rs)))
     (check 'both-duplicates-excluded (and (not (visible? r w 2)) (not (visible? r v 1))))
     (check 'duplicate-dependent-retracted (not (visible? r "childzzz" 1)))
     (check 'duplicate-integrity-visible (assq 'plan-conflict (reduce-noted r)))
     (if final-hash (check 'arrival-order-converges (equal? final-hash (state-hash r)))
         (set! final-hash (state-hash r)))))
 (list (list p a dependent b) (list b dependent a p) (list p b a dependent)))
(define snap (rows->state (state->rows (reduce-records (list p a dependent)))))
(feed snap b)
(check 'snapshot-restores-retraction-evidence (equal? final-hash (state-hash snap)))
(check 'snapshot-dependent-retracted (not (visible? snap "childzzz" 1)))
;; Invalid candidates do not poison a unique valid slot.
(define invalid-other (list v 1 (list (cons w 1)) (put "Wrong") (actor 0 (cons w 1))))
(define mixed (reduce-records (list p a invalid-other)))
(check 'invalid-candidate-does-not-create-duplicate (visible? mixed w 2))
(define extra (list v 1 (list (cons w 1))
  (list 'put (append (cadr (put "Wanted")) '((src . "undeclared")) )) (actor 0 (cons w 1))))
(check 'undeclared-field-is-not-the-planned-intent
  (not (visible? (reduce-records (list p extra)) v 1)))
(define masquerade (list w 1 '() plan (actor 'single #f)))
(check 'plan-cannot-masquerade-as-single
  (assq 'plan-mismatch (reduce-noted (reduce-records (list masquerade)))))
;; Cross-writer transitive causal frontiers cover the earlier plan event.
(define middle (list "middlezz" 1 (list (cons w 2)) (put "Middle") "review"))
(define cross-plan (list 'plan "plan-two" fp after (list (cons 0 intent) (cons 1 intent))))
(define (ca i pe) (list "review" (cons w "plan-two") i fp pe after))
(define cross (reduce-records
  (list (list w 1 '() cross-plan (ca 'plan #f))
        (list w 2 '() (put "Wanted") (ca 0 (cons w 1)))
        middle
        (list v 1 (list (cons "middlezz" 1)) (put "Wanted") (ca 1 (cons w 1))))))
(check 'transitive-plan-order-is-valid (visible? cross v 1))

(define child-intent '(insert ("#%new" 0) #f ((title . "Child"))))
(define parent-plan (list w 1 '() (list 'plan "plan-one" fp after
    (list (cons 0 intent) (cons 1 child-intent))) (actor 'plan #f)))
(define child-member (list w 3 '()
  (list 'put (list '(title . "Child") (cons 'parent (block-id w 2)) '(ord . 0)))
  (actor 1 (cons w 1))))
(define bound (reduce-records (list parent-plan a child-member)))
(check 'planned-backreference-binds-to-created-block (visible? bound w 3))
(define mixed-chain (reduce-records (list parent-plan a invalid-other child-member)))
(check 'invalid-alternative-does-not-block-the-valid-plan-chain (visible? mixed-chain w 3))
(feed bound b)
(check 'late-duplicate-invalidates-planned-backreference (not (visible? bound w 3)))
(define singles (reduce-records
  (list (list w 1 '() (put "Wanted") (actor 'single #f))
        (list v 1 '() (put "Wanted") (actor 'single #f)))))
(check 'duplicate-single-requests-are-both-excluded
  (and (not (visible? singles w 1)) (not (visible? singles v 1))))
;; All argument-taking options use the same opaque token rule.
(for-each (lambda (spec)
  (for-each (lambda (literal)
    (let ((nodes (parse-arguments (car spec) (list (cadr spec) literal))))
      (check 'option-values-are-opaque
        (and (equal? (argument-option nodes (cadr spec)) literal)
             (null? (argument-positionals nodes))))))
    '("--actor" "--store" "--req" "--cursor" "--text")))
  '((insert "--title") (insert "--text") (insert "--actor") (insert "--store")
    (insert "--req") (insert "--cursor") (insert "--under") (insert "--after")
    (set "--if-unchanged") (move "--after") (outline "--depth")))

;; The same gate applies through publish, snapshot and a write-session load.
(define d (string-append root "/store")) (mkdir d)
(check 'init (eq? (car (store-init! d)) 'ok))
(define (publish writer segment records)
  (let ((bytes (string->utf8 (apply string-append
                (map (lambda (r) (utf8->string (encode-record (cadr r) (+ 1789000000000 (cadr r))
                                (list-ref r 4) (caddr r) (storable-encode (list-ref r 3))))) records)))))
    (log-publish! d writer segment bytes (segment-sha bytes))))
(check 'publish-valid (eq? (car (publish w 1 (list p a))) 'published))
(check 'publish-dependent (eq? (car (publish "childzzz" 1 (list dependent))) 'published))
(define before-snapshot (open-and-reduce d))
(snapshot-write! (string-append d "/snap/000001.sexp") (reduce-applied-cut before-snapshot)
  (cons '(block "ghost" ((tomb . #f) (fields) (position)))
        (filter (lambda (row) (not (eq? (car row) 'request-history))) (state->rows before-snapshot))))
(define legacy-reopened (open-and-reduce d))
(check 'legacy-snapshot-falls-back-to-authoritative-log
  (and (visible? legacy-reopened w 2) (not (state-read legacy-reopened "ghost"))))
(check 'snapshot-written (eq? (car (store-snapshot! d "review")) 'written))
(check 'publish-late-duplicate (eq? (car (publish v 1 (list b))) 'published))
(define reopened (open-and-reduce d))
(check 'published-snapshot-retracts (and (not (visible? reopened w 2)) (not (visible? reopened "childzzz" 1))))
(check 'check-reports-plan-conflict (eq? (cadr (assq 'verdict (cdr (store-check d)))) 'damaged))
(define observed #f)
(with-store-write d (lambda (state view) (set! observed (state-hash state)) '()) "review")
(check 'write-load-agrees-with-read (equal? observed (state-hash reopened)))

;; F3: item completion is a request decision, never mere record presence.
(define bid "batch-one")
(define bfp "fingerprint")
(define (ba id sub pe cursor who fingerprint)
  (list who (cons w id) sub fingerprint pe cursor))
(define receipt (list 'batch bid bfp after (list (cons 0 (cons w 1)))))
(define receipt-ev (make-evidence (cons w 1) (ba bid 'plan #f after "review" bfp) '() receipt 'valid-history #t '()))
(define itemid (list 'batch bid 0))
(define (item-ev seq sub pe payload who fingerprint cursor)
  (make-evidence (cons w seq) (ba itemid sub pe cursor who fingerprint) '() payload 'valid-history #t '()))
(define (item-plan intents) (list 'plan itemid bfp (cons w 1) intents))
(define pe (item-ev 2 'plan #f (item-plan (list (cons 0 intent))) "review" bfp (cons w 1)))
(define member-ev (item-ev 3 0 (cons w 2) (put "Wanted") "review" bfp (cons w 1)))
(define (batch es) (batch-state 1 (cons receipt-ev es) bfp after '() #t '()))
(check 'plan-only-is-not-complete (not (eq? (car (batch (list pe))) 'committed)))
(check 'full-plan-is-complete (eq? (car (batch (list pe member-ev))) 'committed))
(check 'empty-plan-is-complete
  (eq? (car (batch (list (item-ev 2 'plan #f (item-plan '()) "review" bfp (cons w 1))))) 'committed))
(check 'single-is-complete
  (eq? (car (batch (list (item-ev 2 'single #f (put "Wanted") "review" bfp (cons w 1))))) 'committed))
(define partial-plan (item-ev 2 'plan #f (item-plan (list (cons 0 intent) (cons 1 intent))) "review" bfp (cons w 1)))
(check 'partial-plan-is-not-complete (not (eq? (car (batch (list partial-plan member-ev))) 'committed)))
(for-each (lambda (fields)
  (check 'receipt-item-immutable-fields-must-match
    (eq? (car (batch (list (item-ev 2 'single #f (put "Wanted") (car fields) (cadr fields) (caddr fields))))) 'unknown)))
  (list (list "other" bfp (cons w 1)) (list "review" "wrong" (cons w 1)) (list "review" bfp (cons w 0))))
(display failures) (display " failures\nq8 complete\n")
(exit (if (= failures 0) 0 1))
