#!r6rs
(import (chezscheme) (theourgia store) (theourgia reduce) (theourgia rpc)
        (theourgia code-project) (theourgia ffi) (theourgia wire) (theourgia log))
(define bad 0)
(define (want label actual expected)
  (if (equal? actual expected) (printf "ok ~a\n" label)
      (begin (set! bad (+ bad 1)) (printf "FAIL ~a: ~s WANT ~s\n" label actual expected))))
(define root (string-append (or (getenv "THEOURGIA_TEST_ROOT") "/tmp") "/resident-" (number->string (get-process-id))))
(mkdir-p! root)
(putenv "THEOURGIA_HOME" (string-append root "/home"))
(define store (string-append root "/store"))
(rpc-dispatch store '(init) "test")
(with-store-write store (lambda (s v) (list '(insert root #f ((kind . section) (src . "old"))))) "test")
;; Dynamic lookup keeps the initial absence a completed red assertion.
(define enable (guard (e (#t #f)) (eval 'store-resident-cache! (environment '(theourgia store)))))
(want "ED-12 resident cache has a real product entry" (procedure? enable) #t)
(when enable
  (enable #t)
  (let* ((first (open-and-reduce store)) (id (cadar (state-datum first)))
         (again (open-and-reduce store)))
    (want "ED-12 identical authenticated history reuses resident reduction" (eq? first again) #t)
    (let* ((writer (car (store-writers store)))
           (path (string-append store "/writers/" writer "/000001.sexp"))
           (raw (call-with-port (open-file-input-port path) get-bytevector-all))
           (frame (decode-line raw)) (payload (storable-decode (list-ref frame 5)))
           (changed (list 'put (map (lambda (field) (if (eq? (car field) 'src) '(src . "alt") field)) (cadr payload))))
           (bytes (encode-record (cadr frame) (caddr frame) (cadddr frame) (list-ref frame 4) (storable-encode changed))))
      (want "ED-12 replacement fixture retains same source byte count" (bytevector-length bytes) (bytevector-length raw))
      (call-with-port (open-file-output-port path (file-options no-fail)) (lambda (p) (put-bytevector p bytes)))
      (want "ED-12 same-number valid frame rewrite invalidates cached source" (code-field (open-and-reduce store) id 'src) "alt"))
    (with-store-write store (lambda (s v) (list (list 'set id 'src "new"))) "test")
    (let ((changed (open-and-reduce store)))
      (want "ED-12 appended history resets resident reduction" (eq? first changed) #f)
      (want "ED-12 appended history is visible after reset" (code-field changed id 'src) "new"))))
(printf "~a failures\nresident complete\n" bad)
(exit (if (zero? bad) 0 1))
