#!r6rs
(import (chezscheme) (theourgia rpc) (theourgia working)
        (theourgia store) (theourgia reduce) (theourgia ffi))
(define failures 0)
(define (want name actual expected)
  (if (equal? actual expected) (printf "ok ~a\n" name)
      (begin (set! failures (+ failures 1))
             (printf "FAIL ~a: ~s WANT ~s\n" name actual expected))))
(define root (string-append (or (getenv "THEOURGIA_TEST_ROOT") "/tmp")
                            "/working-fault-" (number->string (get-process-id))))
(when (file-exists? root) (error 'working2 "Use a fresh test root" root))
(mkdir-p! root)
(putenv "THEOURGIA_HOME" (string-append root "/home"))
(define store (string-append root "/store"))
(define init (rpc-dispatch store '(init) "test"))
(define writer (cadr (assq 'writer (cdr init))))
(define (call . args) (rpc-dispatch store args "test"))
(define made (call 'insert "--title" "A" "--text" "old"))
(define ev (car (cadr (assq 'events (cdr made)))))
(define id (block-id (car ev) (cdr ev)))
(define dir (string-append store "/writers/" writer "/working"))
(define file (string-append dir "/" id))
(define (read-bytes p) (call-with-port (open-file-input-port p) get-bytevector-all))
(define binary (bytevector 255 0 10 128))
(want "WS-15 arbitrary bytes are durable in one envelope"
      (rpc-ok? (working-write! store #f id binary #f)) #t)
(want "WS-15 binary bytes survive reopening" (working-read store #f id) (list 'ok (list 'bytes binary)))
(want "WS-15 a non-text draft is not silently converted on commit"
      (car (call 'commit id)) 'error)
(call 'write id "saved")
(define original (read-bytes file))
(define (shell-quote s)
  (string-append "'" (apply string-append
    (map (lambda (c) (if (char=? c #\') "'\\''" (string c))) (string->list s))) "'"))
(putenv "THEOURGIA_FAULT" (string-append "fsync-fail@working:file=" id))
(define child-status
  (system (string-append "scheme --script test/working-fault-child.ss "
                        (shell-quote store) " " (shell-quote id))))
(putenv "THEOURGIA_FAULT" "")
(want "WS-15 failed fsync never answers saved" child-status 0)
(want "WS-15 failed temporary cannot replace the old envelope" (read-bytes file) original)
(want "WS-26 a failed temporary is not another draft" (car (call 'drafts)) 'ok)
(want "WS-15 reopening reads the old complete value" (call 'read id "--working") '(ok (text "saved")))

(define chmod (foreign-procedure "chmod" (string int) int))
(define getuid (foreign-procedure "getuid" () int))
(when (= 0 (getuid)) (error 'working2 "Permission evidence requires an ordinary user"))
(want "WS-16 deny actual retirement permission" (chmod dir #o555) 0)
(define committed (call 'commit id))
(want "WS-16 log commit succeeds when retirement fails" (rpc-ok? committed) #t)
(want "WS-16 the actual old envelope remains on disk" (read-bytes file) original)
(want "WS-16 leftover is not an active draft after reopen" (call 'drafts) '(ok (items)))
(call 'set id "src" "later-commit")
(want "WS-18 consumption is proved even after a later commit" (call 'drafts) '(ok (items)))
(want "WS-16 an unqualified repeat has nothing to append" (call 'commit) '(ok (items)))
(want "WS-16 restore writable test directory" (chmod dir #o755) 0)
(call 'write id "saved")
(want "WS-17 a later same-byte draft is still a draft"
      (let ((answer (call 'drafts)))
        (if (and (rpc-ok? answer) (pair? (cadr answer)))
            (length (cdr (cadr answer))) answer)) 1)
(want "WS-17 a new version is not the consumed envelope" (equal? (read-bytes file) original) #f)
(call-with-port (open-file-output-port file (file-options no-fail))
  (lambda (p) (put-bytevector p (string->utf8 "(broken"))))
(want "WS-26 corrupt storage is not absence" (cadr (call 'read id "--working")) 'working-unavailable)
(want "WS-26 corrupt storage is visible in the draft list" (cadr (call 'drafts)) 'working-unavailable)
(printf "~a failures\nworking2 complete\n" failures)
(exit (if (= failures 0) 0 1))
