#!r6rs
(import (chezscheme) (theourgia rpc) (theourgia store)
        (theourgia reduce) (theourgia ffi))

(define failures 0)
(define (want name actual expected)
  (if (equal? actual expected)
      (printf "ok ~a\n" name)
      (begin (set! failures (+ failures 1))
             (printf "FAIL ~a: ~s WANT ~s\n" name actual expected))))
(define root (string-append (or (getenv "THEOURGIA_TEST_ROOT") "/tmp")
                            "/working-" (number->string (get-process-id))))
(when (file-exists? root) (error 'working1 "Use a fresh test root" root))
(mkdir-p! root)
(putenv "THEOURGIA_HOME" (string-append root "/home"))
(define store (string-append root "/store"))
(define init (rpc-dispatch store '(init) "test"))
(define writer (cadr (assq 'writer (cdr init))))
(define (call . args) (rpc-dispatch store args "test"))
(define (insert title)
  (let ((a (call 'insert "--title" title "--text" "old")))
    (let ((ev (car (cadr (assq 'events (cdr a)))))) (block-id (car ev) (cdr ev)))))
(define a (insert "A"))
(define b (insert "B"))
(define (src id)
  (cdr (assq 'src (cdr (assq 'fields (state-read (open-and-reduce store) id))))))
(define (hash id) (block-hash (open-and-reduce store) id))
(define (ok? answer) (rpc-ok? answer))
(define (kind answer) (if (and (pair? answer) (pair? (cdr answer))) (cadr answer) answer))
(define (snapshot dir)
  (apply append
    (map (lambda (name)
           (let ((p (string-append dir "/" name)))
             (cond
               ((member name '("working" "working-requests")) '())
               ((file-directory? p) (snapshot p))
               (else (list (cons p (call-with-port (open-file-input-port p)
                                    get-bytevector-all)))))))
         (sort string<? (directory-list dir)))))
(define before (snapshot (string-append store "/writers")))
(define h0 (hash a))
(want "WS-01 write saves outside the log" (ok? (call 'write a "new")) #t)
(want "WS-01 authoritative files remain byte-identical" (snapshot (string-append store "/writers")) before)
(want "WS-02 default read remains committed" (src a) "old")
(want "WS-02 working read returns the draft" (call 'read a "--working") '(ok (text "new")))
(want "WS-14 a later write preserves the baseline" (ok? (call 'write a "newer")) #t)
(want "WS-03 another writer has an independent draft"
      (ok? (call 'write a "other" "--writer" "draft002")) #t)
(want "WS-03 writer reads its own draft" (call 'read a "--working" "--writer" "draft002") '(ok (text "other")))
(want "WS-04 discard is scoped" (ok? (call 'discard a "--writer" "draft002")) #t)
(want "WS-04 another writer's draft survives" (call 'read a "--working") '(ok (text "newer")))

(define cursor (string-append writer ":" (number->string (cdr (assoc writer (reduce-applied-cut (open-and-reduce store)))))))
(define first (call 'commit a "--req" "working-request-1" "--cursor" cursor))
(want "WS-05 fresh commit succeeds" (ok? first) #t)
(want "WS-05 commit applies the saved bytes" (src a) "newer")
(want "WS-11 a new event changes the block hash" (equal? h0 (hash a)) #f)
(want "WS-16 successfully consumed work is absent from drafts" (call 'drafts) '(ok (items)))
(call 'set a "src" "third")
(define after-third (snapshot (string-append store "/writers")))
(define replay (call 'commit a "--req" "working-request-1" "--cursor" cursor))
(printf "replay observation ~s\n" replay)
(want "WS-07 identity is checked before the old baseline" (ok? replay) #t)
(want "WS-07 replay appends nothing" (snapshot (string-append store "/writers")) after-third)
(want "WS-08 a retry does not re-read a newer draft" (ok? (call 'write a "next")) #t)
(want "WS-08 frozen replay still succeeds" (ok? (call 'commit a "--req" "working-request-1" "--cursor" cursor)) #t)
(want "WS-17 replay retains subsequent edits" (call 'read a "--working") '(ok (text "next")))
(want "WS-25 changed retry arguments are refused"
      (kind (call 'commit b "--req" "working-request-1" "--cursor" cursor)) 'req-mismatch)

(call 'set a "src" "concurrent")
(define stale-before (snapshot (string-append store "/writers")))
(define stale (call 'commit a))
(want "WS-06 a stale baseline is refused" (kind stale) 'stale-baseline)
(want "WS-06 stale refusal names the block" (and (pair? stale) (assq 'block (filter pair? (cdr stale))) (cadr (assq 'block (filter pair? (cdr stale))))) a)
(want "WS-06 stale refusal preserves log bytes" (snapshot (string-append store "/writers")) stale-before)
(want "WS-14 ordinary write does not rebase" (begin (call 'write a "merged") (kind (call 'commit a))) 'stale-baseline)
(want "WS-14 explicit rebase advances the baseline" (ok? (call 'write a "merged" "--rebase")) #t)
(want "WS-05 rebased commit succeeds" (ok? (call 'commit a)) #t)
(want "WS-05 rebased bytes are committed" (src a) "merged")

(call 'write a "A2")
(call 'write b "B2")
(call 'set b "src" "B-other")
(define multi-before (snapshot (string-append store "/writers")))
(want "WS-09 a stale final block refuses the whole selection" (kind (call 'commit a b)) 'stale-baseline)
(want "WS-09 no fresh prefix is appended" (snapshot (string-append store "/writers")) multi-before)
(want "WS-09 fresh first block stays unchanged" (src a) "merged")
(call 'write b "B-merged" "--rebase")
(want "WS-09 both fresh blocks commit" (ok? (call 'commit a b)) #t)
(want "WS-09 both contents are present" (list (src a) (src b)) '("A2" "B-merged"))

(call 'write a "A3")
(call 'set b "src" "unrelated")
(want "WS-10 unrelated edits do not stale a draft" (ok? (call 'commit a)) #t)
(want "WS-19 existing direct set remains unconditional" (ok? (call 'set a "src" "direct")) #t)
(want "WS-19 explicit stale --based-on is additive" (kind (call 'set a "src" "bad" "--based-on" h0)) 'stale-baseline)
(want "WS-26 unsafe writer paths are refused" (kind (call 'write a "bad" "--writer" "../bad")) 'bad-request)
(want "WS-26 absence falls back to committed" (call 'read b "--working" "--writer" "draft002") '(ok (text "unrelated")))
(printf "~a failures\nworking1 complete\n" failures)
(exit (if (= failures 0) 0 1))
