#!r6rs
;; Copyright 2026 guenchi
;;
;; Licensed under the Apache License, Version 2.0 (the "License");
;; you may not use this file except in compliance with the License.
;; You may obtain a copy of the License at
;;
;;     http://www.apache.org/licenses/LICENSE-2.0
;;
;; Unless required by applicable law or agreed to in writing, software
;; distributed under the License is distributed on an "AS IS" BASIS,
;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;; See the License for the specific language governing permissions and
;; limitations under the License.
(library (theourgia code-suggest)
  (export suggest-boundaries split-suggest)
  (import (rnrs) (theourgia languages) (theourgia text-code) (theourgia regex)
          (theourgia code-project) (theourgia code-markers) (theourgia trace)
          (only (theourgia log) atomic-write! directory-entry-durable!)
          (only (theourgia ffi) process-id wall-clock-ms file-create-exclusive! link! unlink!))

  ;; Profiles are lexical evidence for suggestions, never import authority.
  ;; A state we cannot prove resets the entire suggestion to one block.
  (define (suggest-boundaries entry bytes)
    (call/cc
      (lambda (return)
        (define (fallback reason offset)
          (return (list '(0) (list (list 'code reason 'byte-offset offset)))))
        (let* ((profile (language-property entry 'suggest-only #f))
               (get (lambda (k default) (language-property profile k default)))
               (kind (get 'top-level #f))
               (pairs (get 'pairs '())) (quotes (get 'quote-delimiters '()))
               (multiline (get 'multiline-quotes '())) (raw-quotes (get 'raw-quotes '()))
               (escape (get 'escaped-character "\\"))
               (block (language-property entry 'block-comment #f))
               (uncertain (get 'uncertain-tokens '()))
               (prefix-patterns (map regex-compile (get 'prefix-lines '())))
               (stack '()) (quoted #f) (comment-depth 0) (continued? #f)
               (fence #f) (pending #f) (boundaries '(0))
               (prefix (source-prefix-size bytes)))
          (define (at-any s i tokens) (find (lambda (t) (string-prefix-at? s t i)) tokens))
          (define (fence-run line)
            (let* ((s (trim-left line)) (indent (- (string-length line) (string-length s))))
              (and (<= indent 3) (> (string-length s) 0) (memv (string-ref s 0) '(#\` #\~))
                   (let loop ((i 1))
                     (if (and (< i (string-length s)) (char=? (string-ref s i) (string-ref s 0))) (loop (+ i 1))
                         (and (>= i 3) (list (string-ref s 0) i (substring s i (string-length s)))))))))
          (define (scan-line line offset)
            (set! continued? #f)
            (let loop ((i 0))
              (if (= i (string-length line))
                  (when (and quoted (not continued?) (not (member quoted multiline))) (fallback 'unclosed-quote (+ offset (bytevector-length (string->utf8 line)))))
                  (let ((c (string-ref line i)))
                    (cond
                      ((> comment-depth 0)
                       (cond ((string-prefix-at? line (cadr block) i)
                              (set! comment-depth (- comment-depth 1)) (loop (+ i (string-length (cadr block)))))
                             ((and (get 'nested-block-comment #f) (string-prefix-at? line (car block) i))
                              (set! comment-depth (+ comment-depth 1)) (loop (+ i (string-length (car block)))))
                             (else (loop (+ i 1)))))
                      (quoted
                       (cond ((and (not (member quoted raw-quotes)) (string-prefix-at? line escape i))
                              (if (= (+ i (string-length escape)) (string-length line))
                                  (set! continued? #t)
                                  (loop (min (string-length line) (+ i (string-length escape) 1)))))
                             ((string-prefix-at? line quoted i)
                              (let ((n (string-length quoted))) (set! quoted #f) (loop (+ i n))))
                             (else (loop (+ i 1)))))
                      ((at-any line i (comment-prefixes entry)) (if #f #f))
                      ((and block (string-prefix-at? line (car block) i))
                       (set! comment-depth 1) (loop (+ i (string-length (car block)))))
                      ((at-any line i uncertain) (fallback 'lexically-uncertain (+ offset (bytevector-length (string->utf8 (substring line 0 i))))))
                      ((at-any line i quotes) => (lambda (q) (set! quoted q) (loop (+ i (string-length q)))))
                      ((exists (lambda (p) (char=? c (string-ref p 0))) pairs)
                       (let ((p (find (lambda (p) (char=? c (string-ref p 0))) pairs)))
                         (set! stack (cons (string-ref p 1) stack)) (loop (+ i 1))))
                      ((exists (lambda (p) (char=? c (string-ref p 1))) pairs)
                       (unless (and (pair? stack) (char=? c (car stack))) (fallback 'unbalanced (+ offset i)))
                       (set! stack (cdr stack)) (loop (+ i 1)))
                      ((string-prefix-at? line escape i)
                       (if (= (+ i (string-length escape)) (string-length line)) (set! continued? #t)
                           (loop (min (string-length line) (+ i (string-length escape) 1)))))
                      (else (loop (+ i 1))))))))
          (unless (and profile (member kind '("paren" "brace" "indent" "fence")))
            (fallback 'unknown-profile 0))
          (unless (safe-utf8 bytes) (fallback 'invalid-utf8 0))
          (for-each
            (lambda (token)
              (let ((s (safe-utf8 bytes)))
                (let loop ((i 0))
                  (when (< i (string-length s))
                    (if (string-prefix-at? s token i) (fallback 'lexically-uncertain (bytevector-length (string->utf8 (substring s 0 i))))
                        (loop (+ i 1))))))) (get 'global-uncertain-tokens '()))
          (for-each
            (lambda (row)
              (let* ((offset (+ prefix (car row)))
                     (line (safe-utf8 (byte-slice bytes offset (+ prefix (cadr row)))))
                     (trimmed (trim-left line))
                     (top? (and (null? stack) (not quoted) (zero? comment-depth) (not continued?)
                                (or (not (string=? kind "indent")) (string=? line trimmed)))))
                (if (string=? kind "fence")
                    (let ((run (fence-run line)))
                      (cond
                        (fence
                         (when (and run (char=? (car run) (car fence)) (>= (cadr run) (cadr fence))
                                    (string=? (trim-left (caddr run)) "")) (set! fence #f)))
                        (run (set! fence run))
                        ((definition-name entry trimmed)
                         (when (> offset (car boundaries)) (set! boundaries (cons offset boundaries))))))
                    (begin
                      (cond
                        ((and top? (definition-name entry trimmed))
                         (let ((start (or pending offset)))
                           (when (> start (car boundaries)) (set! boundaries (cons start boundaries))))
                         (set! pending #f))
                        ((and top? (or (at-any trimmed 0 (comment-prefixes entry))
                                       (and block (string-prefix-at? trimmed (car block) 0))
                                       (exists (lambda (p) (regex-match p trimmed)) prefix-patterns)))
                         (unless pending (set! pending offset)))
                        ((and top? (string=? trimmed "")) (set! pending #f))
                        ((and top? (not (> comment-depth 0))) (set! pending #f)))
                      (scan-line line offset)))))
            (byte-lines (byte-slice bytes prefix (bytevector-length bytes))))
          (when (or (pair? stack) quoted (> comment-depth 0) continued? fence)
            (fallback 'unbalanced (bytevector-length bytes)))
          ;; A protected prefix belongs to the first actual block.
          (list (filter (lambda (n) (or (= n 0) (> n prefix))) (reverse boundaries)) '())))))

  (define counter 0)
  (define (review-path path)
    (set! counter (+ counter 1))
    (let* ((suffix (let loop ((i (- (string-length path) 1)))
                     (cond ((< i 0) "") ((char=? (string-ref path i) #\/) "")
                           ((char=? (string-ref path i) #\.) (substring path i (string-length path)))
                           (else (loop (- i 1)))))))
      (string-append path ".review-" (number->string (process-id)) "-"
                     (number->string (wall-clock-ms)) "-" (number->string counter) suffix)))
  (define (split-suggest path output)
    (guard (e ((and (pair? e) (eq? (car e) 'error)) e))
      (let* ((bytes (read-code-bytes path)) (entry (language-for-path path))
             (suggestion (suggest-boundaries entry bytes)) (cuts (car suggestion))
             (target (or output (review-path path))) (tmp (string-append (review-path path) ".tmp"))
             (entries (map (lambda (from to) (list "new" (byte-slice bytes from to)))
                           cuts (append (cdr cuts) (list (bytevector-length bytes))))))
        (trace-event! 'suggest-scanned path (bytevector-length bytes))
        (unless (equal? bytes (read-code-bytes path)) (projection-failure 'input-changed))
        (unless (file-create-exclusive! tmp) (projection-failure 'review-collision))
        (dynamic-wind
          (lambda () (if #f #f))
          (lambda ()
            (atomic-write! tmp (projection-encode entry #f entries) 'working)
            (when (eq? (link! tmp target) 'exists) (projection-failure 'output-exists))
            (directory-entry-durable! target 'working)
            (list 'ok (list 'working-path target) (list 'boundaries cuts) (list 'warnings (cadr suggestion))))
          (lambda () (guard (e (#t #f)) (unlink! tmp)))))))
)
