#!r6rs
;; Copyright 2026 guenchi
;;
;; Licensed under the Apache License, Version 2.0 (the "License");
;; you may not use this file except in compliance with the License.
;; You may obtain a copy of the License at
;;
;;     http://www.apache.org/licenses/LICENSE-2.0
;;
;; Unless required by applicable law or agreed to in writing, software
;; distributed under the License is distributed on an "AS IS" BASIS,
;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;; See the License for the specific language governing permissions and
;; limitations under the License.
(library (theourgia code-markers)
  (export projection-encode projection-decode marker-line projection-failure projection-header-wrapper?
          projection-control projection-header-line)
  (import (rnrs) (theourgia text-code) (theourgia languages) (theourgia wire)
          (only (theourgia digest) bytevector->hex))

  (define (projection-failure reason . details)
    (raise (append (list 'error 'projection-invalid (list 'reason reason)) details)))
  (define (wrapping entry)
    (let ((line (language-property entry 'line-comment #f))
          (block (language-property entry 'block-comment #f)))
      (cond (line (cons (string-append line " ") ""))
            (block (cons (string-append (car block) " ") (string-append " " (cadr block))))
            (else (cons "# " "")))))
  (define (marker-line entry body)
    (let ((w (wrapping entry))) (string->utf8 (string-append (car w) body (cdr w) "\n"))))
  (define (projection-header-wrapper? entry bytes)
    (exists (lambda (row)
              (let ((f (family entry (byte-slice bytes (car row) (cadr row)))))
                (and f (= (car f) 1) (string-prefix-at? (cadr f) "file " 0))))
            (byte-lines bytes)))
  ;; Family recognition is exact at both ends. All positive @ counts escape.
  ;; The payload grammar is checked only for a single-@ control line.
  (define (family entry bytes)
    (let* ((s (safe-utf8 bytes)) (w (wrapping entry))
           (start (string-length (car w))) (suffix (string-length (cdr w))))
      (and s (string-prefix-at? s (car w) 0)
           (>= (string-length s) (+ start suffix))
           (string-prefix-at? s (cdr w) (- (string-length s) suffix))
           (let ((end (- (string-length s) suffix)))
             (let loop ((i start))
               (if (and (< i end) (char=? (string-ref s i) #\@)) (loop (+ i 1))
                   (and (> i start)
                        (or (string-prefix-at? s "block " i) (string-prefix-at? s "file " i))
                        (list (- i start) (substring s i end) start))))))))
  (define (adjust-line entry b delta)
    (let ((f (family entry b)))
      (if (not f) b
          (let ((at (list-ref f 2)))
            (if (= delta 1)
                (bytes-append (byte-slice b 0 at) #vu8(64) (byte-slice b at (bytevector-length b)))
                (bytes-append (byte-slice b 0 at) (byte-slice b (+ at 1) (bytevector-length b))))))))
  (define (escape-body entry b)
    (apply bytes-append
      (map (lambda (r)
             (bytes-append (adjust-line entry (byte-slice b (car r) (cadr r)) 1)
                           (byte-slice b (cadr r) (caddr r)))) (byte-lines b))))
  (define (ends-lf? b)
    (and (> (bytevector-length b) 0) (= 10 (bytevector-u8-ref b (- (bytevector-length b) 1)))))
  (define (padding b) (if (or (zero? (bytevector-length b)) (ends-lf? b)) 0 1))
  (define (unpad b pad)
    (case pad ((0) b)
      ((1) (unless (ends-lf? b) (projection-failure 'invalid-padding))
           (byte-slice b 0 (- (bytevector-length b) 1)))
      (else (projection-failure 'invalid-padding))))
  (define (hex-decode s)
    (unless (and (<= (string-length s) 65536) (even? (string-length s)))
      (projection-failure 'invalid-header))
    (let ((b (make-bytevector (div (string-length s) 2))))
      (define (digit c)
        (cond ((char<=? #\0 c #\9) (- (char->integer c) 48))
              ((char<=? #\a c #\f) (+ 10 (- (char->integer c) 97)))
              (else (projection-failure 'invalid-header))))
      (do ((i 0 (+ i 2))) ((= i (string-length s)) b)
        (bytevector-u8-set! b (div i 2) (+ (* 16 (digit (string-ref s i))) (digit (string-ref s (+ i 1))))))))
  (define (header-read s)
    (guard (e (#t (projection-failure 'invalid-header)))
      (let ((h (storable-decode (string->sexpr-extended (utf8->string (hex-decode s))))))
        (unless (and (list? h) (= 7 (length h)) (eq? (car h) 'code-projection)
                     (equal? (cadr h) 1) (string? (caddr h)) (string? (cadddr h))
                     (list? (list-ref h 4)) (memq (list-ref h 5) '(text datum))
                     (memv (list-ref h 6) '(0 1))
                     (for-all (lambda (p) (and (pair? p) (string? (car p))
                                              (integer? (cdr p)) (exact? (cdr p)) (>= (cdr p) 0))) (list-ref h 4)))
          (projection-failure 'invalid-header)) h)))
  (define (safe-id? s)
    (and (> (string-length s) 0) (<= (string-length s) 256)
         (for-all (lambda (c) (or (char<=? #\a c #\z) (char<=? #\0 c #\9)
                                  (memv c '(#\. #\- #\_)))) (string->list s))
         (not (member s '("." "..")))))
  (define (block-read s)
    (let* ((n (string-length s))
           (space (let loop ((i 0)) (and (< i n) (if (char=? (string-ref s i) #\space) i (loop (+ i 1))))))
           (id (if space (substring s 0 space) s))
           (tail (and space (substring s space n))))
      (unless (and (safe-id? id) (or (not tail) (member tail '(" pad 0" " pad 1"))))
        (projection-failure 'invalid-marker))
      (list id (if (equal? tail " pad 1") 1 0))))

  (define (projection-control entry content)
    (let ((f (family entry content)))
      (and f (= (car f) 1)
           (if (string-prefix-at? (cadr f) "file " 0)
               (list 'file (header-read (substring (cadr f) 5 (string-length (cadr f)))))
               (cons 'block (block-read (substring (cadr f) 6 (string-length (cadr f)))))))))
  (define (projection-header-line entry header mode pad)
    (let ((hex (bytevector->hex (string->utf8 (sexpr->string-extended
                    (storable-encode (append '(code-projection 1) header (list mode pad))))))))
      (when (> (string-length hex) 65536) (projection-failure 'header-limit))
      (marker-line entry (string-append "@file " hex))))

  ;; Header = (store file cut), entries = ((id-or-new raw-bytes) ...).
  ;; Framing LF belongs to the following marker and is never source text.
  (define (projection-encode entry header entries)
    (let* ((first (if (pair? entries) (cadar entries) #vu8()))
           (prefix-size (source-prefix-size first))
           (prefix (byte-slice first 0 prefix-size))
           (padded (if (= 1 (padding prefix)) (bytes-append prefix #vu8(10)) prefix))
           (head (and header (append '(code-projection 1) header (list 'text (padding prefix)))))
           (initial (if head
                        (bytes-append padded (marker-line entry
                          (string-append "@file " (bytevector->hex (string->utf8
                            (sexpr->string-extended (storable-encode head)))))))
                        padded)))
      (let loop ((xs entries) (first? #t) (previous initial) (out '()))
        (if (null? xs) (apply bytes-append (reverse (cons previous out)))
            (let* ((pad (if (and first? (not header)) (padding prefix) (padding previous)))
                   (body (cadar xs))
                   (body (if first? (byte-slice body prefix-size (bytevector-length body)) body))
                   (mark (marker-line entry (string-append "@block " (caar xs) " pad " (number->string pad))))
                   (part (if (and (= pad 1) (not first?)) (bytes-append previous #vu8(10)) previous)))
              (loop (cdr xs) #f (escape-body entry body) (cons mark (cons part out))))))))

  (define (projection-decode entry bytes)
    (let* ((rows (byte-lines bytes))
           (controlled? (exists (lambda (r) (let ((f (family entry (byte-slice bytes (car r) (cadr r)))))
                                              (and f (= 1 (car f))))) rows)))
      (if (not controlled?) (list #f (list (list "new" bytes)))
          (let loop ((rs rows) (header #f) (current #f) (parts '()) (out '()) (seen? #f))
            (if (null? rs)
                (let ((body (apply bytes-append (reverse parts))))
                  (list header (reverse (if current (cons (list current body) out)
                                            (if (> (bytevector-length body) 0) (cons (list "new" body) out) out)))))
                (let* ((r (car rs)) (content (byte-slice bytes (car r) (cadr r)))
                       (eol (byte-slice bytes (cadr r) (caddr r)))
                       (raw (byte-slice bytes (car r) (caddr r))) (f (family entry content)))
                  (cond
                    ((not f) (loop (cdr rs) header current (cons raw parts) out seen?))
                    ((> (car f) 1) (loop (cdr rs) header current
                                        (cons (bytes-append (adjust-line entry content -1) eol) parts) out seen?))
                    ((string-prefix-at? (cadr f) "file " 0)
                     (when (or header current seen?) (projection-failure 'duplicate-header))
                     (let* ((h (header-read (substring (cadr f) 5 (string-length (cadr f)))))
                            (prefix (unpad (apply bytes-append (reverse parts)) (list-ref h 6))))
                       (unless (= (bytevector-length prefix) (source-prefix-size prefix))
                         (projection-failure 'misplaced-header))
                       (loop (cdr rs) h #f (list prefix) out #t)))
                    (else
                     (let* ((mark (block-read (substring (cadr f) 6 (string-length (cadr f)))))
                            (body (unpad (apply bytes-append (reverse parts)) (cadr mark)))
                            (prefix? (and (not current) (or header (= (bytevector-length body) (source-prefix-size body))))))
                       (loop (cdr rs) header (car mark) (if prefix? (list body) '())
                             (if current (cons (list current body) out)
                                 (if (and (not prefix?) (> (bytevector-length body) 0)) (cons (list "new" body) out) out)) #t))))))))))
)
