#!r6rs
(library (theourgia evidence-index)
  (export indexed-records index-checkpoint! index-forget-memory!)
  (import (rnrs) (theourgia request) (theourgia wire)
          (only (theourgia digest) sha256 bytevector->hex)
          (only (theourgia ffi) directory-entries file-is-directory? path-version trace-event!)
          (only (theourgia log) store-writers writer-directory store-id-of
                enumerate-segment-files segment-file-name read-manifest manifest-segments
                discover-prefix discovery-quarantine atomic-write!))

  ;; The checkpoint is disposable, checksummed localization data. The frame
  ;; at each hit is reread and decoded; cached bytes can only yield unknown
  ;; when their authoritative location disappeared, never a replay proof.
  (define caches (make-hashtable string-hash string=?))
  (define (encode x) (string->utf8 (sexpr->string-extended (storable-encode x))))
  (define (digest x) (bytevector->hex (sha256 (encode x))))
  (define (key x) (sexpr->string-extended x))
  (define (table) (make-hashtable string-hash string=?))
  (define (read-bytes path)
    (call-with-port (open-file-input-port path)
      (lambda (p) (let ((b (get-bytevector-all p))) (if (eof-object? b) #vu8() b)))))
  (define (files dir)
    (if (file-is-directory? dir)
        (map (lambda (n) (string-append dir "/" n)) (list-sort string<? (directory-entries dir))) '()))
  (define (segment-paths store writer)
    (map (lambda (n) (string-append (writer-directory store writer) "/" (segment-file-name n)))
         (enumerate-segment-files store writer)))
  (define (inventory store)
    (map (lambda (p) (cons p (and (file-exists? p) (path-version p))))
      (append (list (string-append store "/meta.sexp") (string-append store "/instance.sexp"))
        (apply append
          (map (lambda (w)
                 (let ((d (writer-directory store w)))
                   (append (map (lambda (n) (string-append d "/" n))
                                '("owner.sexp" "retired.sexp" "published.sexp" "quarantine.sexp"))
                           (segment-paths store w) (files (string-append d "/damaged"))
                           (files (string-append d "/incoming"))))) (store-writers store))))))
  (define (subbytes b from to)
    (let ((out (make-bytevector (- to from))))
      (bytevector-copy! b from out 0 (- to from)) out))
  (define (frame-record writer bytes placement)
    (let ((r (decode-line bytes)))
      (and (pair? r) (eq? (car r) 'ok)
           (list (cons writer (cadr r)) (cadddr r) (list-ref r 4)
                 (storable-decode (list-ref r 5)) placement))))
  (define (entry-record e) (frame-record (cadr e) (cadddr e) (list-ref e 4)))
  (define (scan path writer placement fork)
    (let ((bytes (read-bytes path)))
      (let loop ((start 0) (i 0) (out '()))
        (cond
          ((= i (bytevector-length bytes)) (reverse out))
          ((= (bytevector-u8-ref bytes i) 10)
           (let* ((raw (subbytes bytes start (+ i 1)))
                  (rec (frame-record writer raw placement)))
             (trace-event! 'identity-source-decode path (bytevector-length raw))
             (loop (+ i 1) (+ i 1)
                   (if rec (cons (list path writer start raw
                                      (if (and fork (>= (cdar rec) fork)) 'quarantined placement)) out) out))))
          (else (loop start (+ i 1) out))))))
  (define (scan-store store)
    (apply append
      (map (lambda (w)
             (let* ((d (writer-directory store w)) (manifest (read-manifest store w))
                    (listed (manifest-segments manifest))
                    (p (discover-prefix store w 'shared)) (q (discovery-quarantine p))
                    (fork (and (pair? q) (cadr q))))
               (append
                 (apply append (map (lambda (n)
                                      (scan (string-append d "/" (segment-file-name n)) w
                                            (if (or (not manifest) (memv n listed)) 'valid-history 'unlisted) fork))
                                    (enumerate-segment-files store w)))
                 (apply append (map (lambda (p) (scan p w 'damaged #f)) (files (string-append d "/damaged"))))
                 (apply append (map (lambda (p) (scan p w 'incoming #f)) (files (string-append d "/incoming")))))))
           (store-writers store))))
  (define (add-bucket! buckets id entry)
    (let ((k (key id))) (hashtable-set! buckets k (cons entry (hashtable-ref buckets k '())))))
  (define (buckets-for entries)
    (let ((buckets (table)))
      (for-each
        (lambda (e)
          (let* ((rec (entry-record e)) (actor (and rec (cadr rec))))
            (when (request-actor? actor)
              (add-bucket! buckets (actor-identity actor) e)
              (when (and (resolution? (cadddr rec))
                         (not (equal? (actor-identity actor) (resolution-target (cadddr rec)))))
                (add-bucket! buckets (resolution-target (cadddr rec)) e))))) entries)
      buckets))
  (define (checkpoint-path store) (string-append store "/request-index.sexp"))
  (define (entry? e store)
    (and (list? e) (= (length e) 5) (string? (car e)) (string? (cadr e))
         (integer? (caddr e)) (exact? (caddr e)) (>= (caddr e) 0) (bytevector? (cadddr e))
         (memq (list-ref e 4) '(valid-history unlisted quarantined damaged incoming index-evidence-missing))
         (let ((prefix (string-append (writer-directory store (cadr e)) "/")))
           (and (> (string-length (car e)) (string-length prefix))
                (string=? prefix (substring (car e) 0 (string-length prefix)))
                ;; Only enumerated store paths can appear in a localization hint.
                (not (let loop ((i 0))
                       (and (< (+ i 1) (string-length (car e)))
                            (or (string=? ".." (substring (car e) i (+ i 2))) (loop (+ i 1))))))))
         (entry-record e)))
  (define (load-checkpoint store)
    (guard (e (#t #f))
      (let* ((x (storable-decode (string->sexpr-extended (utf8->string (read-bytes (checkpoint-path store))))))
             (body (and (list? x) (= (length x) 5) (list-ref x 4))))
        (and body (eq? (car x) 'request-index) (eqv? (cadr x) 1)
             (equal? (caddr x) (store-id-of store)) (equal? (cadddr x) (digest body))
             (list? body) (= (length body) 2) (list? (car body)) (list? (cadr body))
             (for-all (lambda (e) (entry? e store)) (cadr body))
             (vector (car body) (cadr body) (buckets-for (cadr body)))))))
  (define (frame-key e) (string-append (cadr e) ":" (bytevector->hex (sha256 (cadddr e)))))
  (define (retain-missing old current)
    (let ((present (table)))
      (for-each (lambda (e) (hashtable-set! present (frame-key e) #t)) current)
      (append current
        (map (lambda (e) (list (car e) (cadr e) (caddr e) (cadddr e) 'index-evidence-missing))
             (filter (lambda (e) (not (hashtable-contains? present (frame-key e)))) old)))))
  (define (ensure-index store)
    (let* ((cache-key (key (list store (store-id-of store))))
           (stamp (inventory store))
           (old (or (hashtable-ref caches cache-key #f) (load-checkpoint store))))
      (if (and old (equal? stamp (vector-ref old 0)))
          (begin (hashtable-set! caches cache-key old) old)
          (let* ((current (scan-store store))
                 (entries (if old (retain-missing (vector-ref old 1) current) current))
                 (fresh (vector stamp entries (buckets-for entries))))
            (hashtable-set! caches cache-key fresh) fresh))))
  (define (verified-record e)
    (let ((actual (guard (failure (#t #f))
                    (call-with-port (open-file-input-port (car e))
                      (lambda (p)
                        (set-port-position! p (caddr e))
                        (get-bytevector-n p (bytevector-length (cadddr e))))))))
      (trace-event! 'identity-source-decode (car e) (and (bytevector? actual) (bytevector-length actual)))
      (if (and (not (eq? (list-ref e 4) 'index-evidence-missing)) (equal? actual (cadddr e)))
          (frame-record (cadr e) actual (list-ref e 4))
          (frame-record (cadr e) (cadddr e) 'index-evidence-missing))))
  (define (indexed-records store identity)
    (let ((idx (ensure-index store)))
      (map verified-record (reverse (hashtable-ref (vector-ref idx 2) (key identity) '())))))
  (define (index-checkpoint! store)
    (let* ((idx (ensure-index store)) (body (list (vector-ref idx 0) (vector-ref idx 1))))
      (atomic-write! (checkpoint-path store)
                    (encode (list 'request-index 1 (store-id-of store) (digest body) body)) 'index)))
  (define (index-forget-memory!) (hashtable-clear! caches))
)
