;; Copyright 2026 guenchi
;;
;; Licensed under the Apache License, Version 2.0 (the "License");
;; you may not use this file except in compliance with the License.
;; You may obtain a copy of the License at
;;
;;     http://www.apache.org/licenses/LICENSE-2.0
;;
;; Unless required by applicable law or agreed to in writing, software
;; distributed under the License is distributed on an "AS IS" BASIS,
;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;; See the License for the specific language governing permissions and
;; limitations under the License.

;;; (theourgia platform-numbers) -- every number the FFI reads that a
;;; platform decides, as MEASURED data, one row per platform.
;;;
;;; KEY: A ROW IS A READING, NOT A TRANSCRIPTION. Each row below is the
;;; output of test/probe/layout.c on that platform, byte for byte as the
;;; probe printed it (the archived files are under test/probe/readings/,
;;; and a row of the suite compares each row with its file). The code
;;; asks this library for a number by name -- (platform-number 'O_APPEND),
;;; (platform-field 'stat 'st_mode 'offset) -- and never writes one down:
;;; a number written into the code is a claim about one platform that
;;; reads as true on all of them, and the first Linux run found seven such
;;; claims false, one of which wrote every log record over the start of
;;; its segment.
;;;
;;; THE ROW IS SELECTED ONCE, WHEN THIS LIBRARY IS INITIALISED, from what
;;; Chez gives with no foreign call: (machine-type) names the system and
;;; the architecture, and on Linux the C library is read from the objects
;;; this process has mapped (/proc/self/maps), glibc and musl each
;;; identified by name. ffi.sc imports this library, so the selection
;;; happens before ffi.sc's body makes its first foreign call.
;;;
;;; NEVER: A PLATFORM WITHOUT A ROW IS REFUSED, NOT SERVED A NEIGHBOUR'S.
;;; A neighbouring row is the failure this library exists to end -- the
;;; right offsets for another machine. So an unlisted platform (another
;;; architecture, macOS on x86_64 or under Rosetta, a Linux with musl, a
;;; process that cannot read /proc/self/maps) writes
;;;   (error platform-unmeasured (system ...) (machine ...) (remedy ...))
;;; on the standard error and exits 75, before anything else runs. It
;;; cannot answer the ordinary way: nothing that renders an answer has
;;; been loaded, and the standard output of the MCP shell is its protocol
;;; stream. The remedy is the probe: run test/probe/layout.c there and add
;;; its output as a row.
;;;
;;; NOTE: A NUMBER A PLATFORM DOES NOT HAVE IS `absent` IN ITS ROW, and
;;; asking for it is a programming error (an assertion), not a refusal:
;;; the code reads such a number only inside the branch for the platform
;;; that has it (F_FULLFSYNC on macOS, the sysctl names on FreeBSD).
;;;
;;; This library imports nothing of the tree: it is below every one of
;;; them.

(library (theourgia platform-numbers)
  (export platform-number platform-field platform-field-present?
          platform-struct-size platform-struct-value platform-type-size
          platform-wait-sample platform-key platform-row platform-readings
          reading-key maps-libc)
  (import (chezscheme))

  ;; ---- the rows ------------------------------------------------------------

  (define readings
  (list
    ;; Linux x86_64, glibc 2.39: GitHub Actions ubuntu-latest, run 36600347509 (linux-ubuntu-latest.sexp).
    '(
      (layout-probe 4)
      (machine "x86_64") (system "Linux") (release "6.17.0-1022-azure")
      (libc "glibc 2.39")
      (pointer-size 8)
      (struct stat (size 144)
        (field st_dev (offset 0) (size 8))
        (field st_ino (offset 8) (size 8))
        (field st_mode (offset 24) (size 4))
        (field st_nlink (offset 16) (size 8))
        (field st_uid (offset 28) (size 4))
        (field st_gid (offset 32) (size 4))
        (field st_size (offset 48) (size 8))
        (field st_blksize (offset 56) (size 8))
        (field st_blocks (offset 64) (size 8))
        (field st_atim (member st_atim) (offset 72) (size 16))
        (field st_mtim (member st_mtim) (offset 88) (size 16))
        (field st_ctim (member st_ctim) (offset 104) (size 16))
        (type dev_t (size 8))
        (type ino_t (size 8))
        (type mode_t (size 4))
        (type nlink_t (size 8))
        (type uid_t (size 4))
        (type gid_t (size 4))
        (type off_t (size 8))
        (type blksize_t (size 8))
        (type blkcnt_t (size 8))
        (type time_t (size 8))
        (type struct timespec (size 16))
        (field-of-timespec tv_nsec (offset 8) (size 8)))
      (struct sockaddr_un (size 110)
        (field sun_len absent)
        (field sun_family (offset 0) (size 2))
        (field sun_path (offset 2) (size 108))
        (type sa_family_t (size 2))
        (af-unix 1)
        (sun-len "/nonexistent/theourgia-layout-probe/socket" 44))
      (struct dirent (size 280)
        (field d_ino (offset 0) (size 8))
        (field d_type (offset 18) (size 1))
        (field d_namlen absent)
        (field d_reclen (offset 16) (size 2))
        (field d_name (offset 19) (size 256))
        )
      (struct timeval (size 16)
        (field tv_sec (offset 0) (size 8))
        (field tv_usec (offset 8) (size 8))
        )
      (struct rlimit (size 16)
        (field rlim_cur (offset 0) (size 8))
        (field rlim_max (offset 8) (size 8))
        (RLIM_INFINITY 18446744073709551615))
      (types (pid_t (size 4)) (int (size 4)))
      (struct proc_taskinfo absent)
      (struct kinfo_proc absent)
      (struct posix_spawn (attr-size 336) (file-actions-size 80))
      (wait-status (WEXITSTATUS-0x0300 3) (WIFEXITED-0x0300 1) (WTERMSIG-0x0009 9) (WIFSIGNALED-0x0009 1))
      (constants
        (X_OK 1)
        (F_OK 0)
        (PATH_MAX 4096)
        (PROC_PIDTASKINFO absent)
        (O_RDONLY 0)
        (O_WRONLY 1)
        (O_RDWR 2)
        (O_CREAT 64)
        (O_TRUNC 512)
        (O_EXCL 128)
        (O_APPEND 1024)
        (O_CLOEXEC 524288)
        (O_NOFOLLOW 131072)
        (O_DIRECTORY 65536)
        (O_NONBLOCK 2048)
        (FIOCLEX 21585)
        (FIONCLEX 21584)
        (F_GETFD 1)
        (F_SETFD 2)
        (FD_CLOEXEC 1)
        (F_GETFL 3)
        (F_SETFL 4)
        (F_DUPFD 0)
        (F_FULLFSYNC absent)
        (_SC_NPROCESSORS_ONLN 84)
        (_SC_PAGESIZE 30)
        (_PC_CASE_SENSITIVE absent)
        (LOCK_SH 1)
        (LOCK_EX 2)
        (LOCK_NB 4)
        (LOCK_UN 8)
        (SEEK_SET 0)
        (SEEK_CUR 1)
        (SEEK_END 2)
        (S_IFMT 61440)
        (S_IFDIR 16384)
        (S_IFREG 32768)
        (S_IFLNK 40960)
        (S_IFSOCK 49152)
        (AF_UNIX 1)
        (SOCK_STREAM 1)
        (SOL_SOCKET 1)
        (SO_RCVTIMEO 20)
        (SO_SNDTIMEO 21)
        (SO_REUSEADDR 2)
        (SIGTERM 15)
        (SIGKILL 9)
        (SIGINT 2)
        (SIGHUP 1)
        (SIGCHLD 17)
        (SIGPIPE 13)
        (WNOHANG 1)
        (RLIMIT_CPU 0)
        (RLIMIT_AS 9)
        (POSIX_SPAWN_SETSID absent)
        (POSIX_SPAWN_CLOEXEC_DEFAULT absent)
        (POSIX_SPAWN_SETPGROUP 2)
        (CTL_KERN absent)
        (KERN_PROC absent)
        (KERN_PROC_PID absent)
        (EPERM 1)
        (ENOENT 2)
        (ESRCH 3)
        (EINTR 4)
        (EIO 5)
        (EBADF 9)
        (ECHILD 10)
        (EAGAIN 11)
        (EWOULDBLOCK 11)
        (EACCES 13)
        (EEXIST 17)
        (ENOTDIR 20)
        (EISDIR 21)
        (EINVAL 22)
        (EMFILE 24)
        (ENOTTY 25)
        (ENOSPC 28)
        (EROFS 30)
        (EPIPE 32)
        (ENAMETOOLONG 36)
        (ENOTEMPTY 39)
        (ELOOP 40)
        (EOVERFLOW 75)
        (ETIMEDOUT 110)
        (ECONNREFUSED 111)
        (ENOTSOCK 88)
        ))
    ;; Linux aarch64, glibc 2.39: GitHub Actions ubuntu-24.04-arm, run 36600347509 (linux-ubuntu-2404-arm.sexp).
    '(
      (layout-probe 4)
      (machine "aarch64") (system "Linux") (release "6.17.0-1022-azure")
      (libc "glibc 2.39")
      (pointer-size 8)
      (struct stat (size 128)
        (field st_dev (offset 0) (size 8))
        (field st_ino (offset 8) (size 8))
        (field st_mode (offset 16) (size 4))
        (field st_nlink (offset 20) (size 4))
        (field st_uid (offset 24) (size 4))
        (field st_gid (offset 28) (size 4))
        (field st_size (offset 48) (size 8))
        (field st_blksize (offset 56) (size 4))
        (field st_blocks (offset 64) (size 8))
        (field st_atim (member st_atim) (offset 72) (size 16))
        (field st_mtim (member st_mtim) (offset 88) (size 16))
        (field st_ctim (member st_ctim) (offset 104) (size 16))
        (type dev_t (size 8))
        (type ino_t (size 8))
        (type mode_t (size 4))
        (type nlink_t (size 4))
        (type uid_t (size 4))
        (type gid_t (size 4))
        (type off_t (size 8))
        (type blksize_t (size 4))
        (type blkcnt_t (size 8))
        (type time_t (size 8))
        (type struct timespec (size 16))
        (field-of-timespec tv_nsec (offset 8) (size 8)))
      (struct sockaddr_un (size 110)
        (field sun_len absent)
        (field sun_family (offset 0) (size 2))
        (field sun_path (offset 2) (size 108))
        (type sa_family_t (size 2))
        (af-unix 1)
        (sun-len "/nonexistent/theourgia-layout-probe/socket" 44))
      (struct dirent (size 280)
        (field d_ino (offset 0) (size 8))
        (field d_type (offset 18) (size 1))
        (field d_namlen absent)
        (field d_reclen (offset 16) (size 2))
        (field d_name (offset 19) (size 256))
        )
      (struct timeval (size 16)
        (field tv_sec (offset 0) (size 8))
        (field tv_usec (offset 8) (size 8))
        )
      (struct rlimit (size 16)
        (field rlim_cur (offset 0) (size 8))
        (field rlim_max (offset 8) (size 8))
        (RLIM_INFINITY 18446744073709551615))
      (types (pid_t (size 4)) (int (size 4)))
      (struct proc_taskinfo absent)
      (struct kinfo_proc absent)
      (struct posix_spawn (attr-size 336) (file-actions-size 80))
      (wait-status (WEXITSTATUS-0x0300 3) (WIFEXITED-0x0300 1) (WTERMSIG-0x0009 9) (WIFSIGNALED-0x0009 1))
      (constants
        (X_OK 1)
        (F_OK 0)
        (PATH_MAX 4096)
        (PROC_PIDTASKINFO absent)
        (O_RDONLY 0)
        (O_WRONLY 1)
        (O_RDWR 2)
        (O_CREAT 64)
        (O_TRUNC 512)
        (O_EXCL 128)
        (O_APPEND 1024)
        (O_CLOEXEC 524288)
        (O_NOFOLLOW 32768)
        (O_DIRECTORY 16384)
        (O_NONBLOCK 2048)
        (FIOCLEX 21585)
        (FIONCLEX 21584)
        (F_GETFD 1)
        (F_SETFD 2)
        (FD_CLOEXEC 1)
        (F_GETFL 3)
        (F_SETFL 4)
        (F_DUPFD 0)
        (F_FULLFSYNC absent)
        (_SC_NPROCESSORS_ONLN 84)
        (_SC_PAGESIZE 30)
        (_PC_CASE_SENSITIVE absent)
        (LOCK_SH 1)
        (LOCK_EX 2)
        (LOCK_NB 4)
        (LOCK_UN 8)
        (SEEK_SET 0)
        (SEEK_CUR 1)
        (SEEK_END 2)
        (S_IFMT 61440)
        (S_IFDIR 16384)
        (S_IFREG 32768)
        (S_IFLNK 40960)
        (S_IFSOCK 49152)
        (AF_UNIX 1)
        (SOCK_STREAM 1)
        (SOL_SOCKET 1)
        (SO_RCVTIMEO 20)
        (SO_SNDTIMEO 21)
        (SO_REUSEADDR 2)
        (SIGTERM 15)
        (SIGKILL 9)
        (SIGINT 2)
        (SIGHUP 1)
        (SIGCHLD 17)
        (SIGPIPE 13)
        (WNOHANG 1)
        (RLIMIT_CPU 0)
        (RLIMIT_AS 9)
        (POSIX_SPAWN_SETSID absent)
        (POSIX_SPAWN_CLOEXEC_DEFAULT absent)
        (POSIX_SPAWN_SETPGROUP 2)
        (CTL_KERN absent)
        (KERN_PROC absent)
        (KERN_PROC_PID absent)
        (EPERM 1)
        (ENOENT 2)
        (ESRCH 3)
        (EINTR 4)
        (EIO 5)
        (EBADF 9)
        (ECHILD 10)
        (EAGAIN 11)
        (EWOULDBLOCK 11)
        (EACCES 13)
        (EEXIST 17)
        (ENOTDIR 20)
        (EISDIR 21)
        (EINVAL 22)
        (EMFILE 24)
        (ENOTTY 25)
        (ENOSPC 28)
        (EROFS 30)
        (EPIPE 32)
        (ENAMETOOLONG 36)
        (ENOTEMPTY 39)
        (ELOOP 40)
        (EOVERFLOW 75)
        (ETIMEDOUT 110)
        (ECONNREFUSED 111)
        (ENOTSOCK 88)
        ))
    ;; FreeBSD 15.0 amd64: the Paris server (freebsd-15-paris.sexp).
    '(
      (layout-probe 4)
      (machine "amd64") (system "FreeBSD") (release "15.0-RELEASE")
      (libc "freebsd 15")
      (pointer-size 8)
      (struct stat (size 224)
        (field st_dev (offset 0) (size 8))
        (field st_ino (offset 8) (size 8))
        (field st_mode (offset 24) (size 2))
        (field st_nlink (offset 16) (size 8))
        (field st_uid (offset 28) (size 4))
        (field st_gid (offset 32) (size 4))
        (field st_size (offset 112) (size 8))
        (field st_blksize (offset 128) (size 4))
        (field st_blocks (offset 120) (size 8))
        (field st_atim (member st_atim) (offset 48) (size 16))
        (field st_mtim (member st_mtim) (offset 64) (size 16))
        (field st_ctim (member st_ctim) (offset 80) (size 16))
        (type dev_t (size 8))
        (type ino_t (size 8))
        (type mode_t (size 2))
        (type nlink_t (size 8))
        (type uid_t (size 4))
        (type gid_t (size 4))
        (type off_t (size 8))
        (type blksize_t (size 4))
        (type blkcnt_t (size 8))
        (type time_t (size 8))
        (type struct timespec (size 16))
        (field-of-timespec tv_nsec (offset 8) (size 8)))
      (struct sockaddr_un (size 106)
        (field sun_len (offset 0) (size 1))
        (field sun_family (offset 1) (size 1))
        (field sun_path (offset 2) (size 104))
        (type sa_family_t (size 1))
        (af-unix 1)
        (sun-len "/nonexistent/theourgia-layout-probe/socket" 44))
      (struct dirent (size 280)
        (field d_ino (offset 0) (size 8))
        (field d_type (offset 18) (size 1))
        (field d_namlen (offset 20) (size 2))
        (field d_reclen (offset 16) (size 2))
        (field d_name (offset 24) (size 256))
        )
      (struct timeval (size 16)
        (field tv_sec (offset 0) (size 8))
        (field tv_usec (offset 8) (size 8))
        )
      (struct rlimit (size 16)
        (field rlim_cur (offset 0) (size 8))
        (field rlim_max (offset 8) (size 8))
        (RLIM_INFINITY 9223372036854775807))
      (types (pid_t (size 4)) (int (size 4)))
      (struct proc_taskinfo absent)
      (struct kinfo_proc (size 1088)
        (field ki_rssize (offset 264) (size 8))
        )
      (struct posix_spawn (attr-size 8) (file-actions-size 8))
      (wait-status (WEXITSTATUS-0x0300 3) (WIFEXITED-0x0300 1) (WTERMSIG-0x0009 9) (WIFSIGNALED-0x0009 1))
      (constants
        (X_OK 1)
        (F_OK 0)
        (PATH_MAX 1024)
        (PROC_PIDTASKINFO absent)
        (O_RDONLY 0)
        (O_WRONLY 1)
        (O_RDWR 2)
        (O_CREAT 512)
        (O_TRUNC 1024)
        (O_EXCL 2048)
        (O_APPEND 8)
        (O_CLOEXEC 1048576)
        (O_NOFOLLOW 256)
        (O_DIRECTORY 131072)
        (O_NONBLOCK 4)
        (FIOCLEX 536897025)
        (FIONCLEX 536897026)
        (F_GETFD 1)
        (F_SETFD 2)
        (FD_CLOEXEC 1)
        (F_GETFL 3)
        (F_SETFL 4)
        (F_DUPFD 0)
        (F_FULLFSYNC absent)
        (_SC_NPROCESSORS_ONLN 58)
        (_SC_PAGESIZE 47)
        (_PC_CASE_SENSITIVE absent)
        (LOCK_SH 1)
        (LOCK_EX 2)
        (LOCK_NB 4)
        (LOCK_UN 8)
        (SEEK_SET 0)
        (SEEK_CUR 1)
        (SEEK_END 2)
        (S_IFMT 61440)
        (S_IFDIR 16384)
        (S_IFREG 32768)
        (S_IFLNK 40960)
        (S_IFSOCK 49152)
        (AF_UNIX 1)
        (SOCK_STREAM 1)
        (SOL_SOCKET 65535)
        (SO_RCVTIMEO 4102)
        (SO_SNDTIMEO 4101)
        (SO_REUSEADDR 4)
        (SIGTERM 15)
        (SIGKILL 9)
        (SIGINT 2)
        (SIGHUP 1)
        (SIGCHLD 20)
        (SIGPIPE 13)
        (WNOHANG 1)
        (RLIMIT_CPU 0)
        (RLIMIT_AS 10)
        (POSIX_SPAWN_SETSID absent)
        (POSIX_SPAWN_CLOEXEC_DEFAULT absent)
        (POSIX_SPAWN_SETPGROUP 2)
        (CTL_KERN 1)
        (KERN_PROC 14)
        (KERN_PROC_PID 1)
        (EPERM 1)
        (ENOENT 2)
        (ESRCH 3)
        (EINTR 4)
        (EIO 5)
        (EBADF 9)
        (ECHILD 10)
        (EAGAIN 35)
        (EWOULDBLOCK 35)
        (EACCES 13)
        (EEXIST 17)
        (ENOTDIR 20)
        (EISDIR 21)
        (EINVAL 22)
        (EMFILE 24)
        (ENOTTY 25)
        (ENOSPC 28)
        (EROFS 30)
        (EPIPE 32)
        (ENAMETOOLONG 63)
        (ENOTEMPTY 66)
        (ELOOP 62)
        (EOVERFLOW 84)
        (ETIMEDOUT 60)
        (ECONNREFUSED 61)
        (ENOTSOCK 38)
        ))
    ;; Darwin arm64, macOS 25.3: the development machine (darwin-arm64-local.sexp).
    '(
      (layout-probe 4)
      (machine "arm64") (system "Darwin") (release "25.3.0")
      (libc "darwin")
      (pointer-size 8)
      (struct stat (size 144)
        (field st_dev (offset 0) (size 4))
        (field st_ino (offset 8) (size 8))
        (field st_mode (offset 4) (size 2))
        (field st_nlink (offset 6) (size 2))
        (field st_uid (offset 16) (size 4))
        (field st_gid (offset 20) (size 4))
        (field st_size (offset 96) (size 8))
        (field st_blksize (offset 112) (size 4))
        (field st_blocks (offset 104) (size 8))
        (field st_atim (member st_atimespec) (offset 32) (size 16))
        (field st_mtim (member st_mtimespec) (offset 48) (size 16))
        (field st_ctim (member st_ctimespec) (offset 64) (size 16))
        (type dev_t (size 4))
        (type ino_t (size 8))
        (type mode_t (size 2))
        (type nlink_t (size 2))
        (type uid_t (size 4))
        (type gid_t (size 4))
        (type off_t (size 8))
        (type blksize_t (size 4))
        (type blkcnt_t (size 8))
        (type time_t (size 8))
        (type struct timespec (size 16))
        (field-of-timespec tv_nsec (offset 8) (size 8)))
      (struct sockaddr_un (size 106)
        (field sun_len (offset 0) (size 1))
        (field sun_family (offset 1) (size 1))
        (field sun_path (offset 2) (size 104))
        (type sa_family_t (size 1))
        (af-unix 1)
        (sun-len "/nonexistent/theourgia-layout-probe/socket" 44))
      (struct dirent (size 1048)
        (field d_ino (offset 0) (size 8))
        (field d_type (offset 20) (size 1))
        (field d_namlen (offset 18) (size 2))
        (field d_reclen (offset 16) (size 2))
        (field d_name (offset 21) (size 1024))
        )
      (struct timeval (size 16)
        (field tv_sec (offset 0) (size 8))
        (field tv_usec (offset 8) (size 4))
        )
      (struct rlimit (size 16)
        (field rlim_cur (offset 0) (size 8))
        (field rlim_max (offset 8) (size 8))
        (RLIM_INFINITY 9223372036854775807))
      (types (pid_t (size 4)) (int (size 4)))
      (struct proc_taskinfo (size 96)
        (field pti_virtual_size (offset 0) (size 8))
        (field pti_resident_size (offset 8) (size 8))
        )
      (struct kinfo_proc (size 648)
        (field ki_rssize absent)
        )
      (struct posix_spawn (attr-size 8) (file-actions-size 8))
      (wait-status (WEXITSTATUS-0x0300 3) (WIFEXITED-0x0300 1) (WTERMSIG-0x0009 9) (WIFSIGNALED-0x0009 1))
      (constants
        (X_OK 1)
        (F_OK 0)
        (PATH_MAX 1024)
        (PROC_PIDTASKINFO 4)
        (O_RDONLY 0)
        (O_WRONLY 1)
        (O_RDWR 2)
        (O_CREAT 512)
        (O_TRUNC 1024)
        (O_EXCL 2048)
        (O_APPEND 8)
        (O_CLOEXEC 16777216)
        (O_NOFOLLOW 256)
        (O_DIRECTORY 1048576)
        (O_NONBLOCK 4)
        (FIOCLEX 536897025)
        (FIONCLEX 536897026)
        (F_GETFD 1)
        (F_SETFD 2)
        (FD_CLOEXEC 1)
        (F_GETFL 3)
        (F_SETFL 4)
        (F_DUPFD 0)
        (F_FULLFSYNC 51)
        (_SC_NPROCESSORS_ONLN 58)
        (_SC_PAGESIZE 29)
        (_PC_CASE_SENSITIVE 11)
        (LOCK_SH 1)
        (LOCK_EX 2)
        (LOCK_NB 4)
        (LOCK_UN 8)
        (SEEK_SET 0)
        (SEEK_CUR 1)
        (SEEK_END 2)
        (S_IFMT 61440)
        (S_IFDIR 16384)
        (S_IFREG 32768)
        (S_IFLNK 40960)
        (S_IFSOCK 49152)
        (AF_UNIX 1)
        (SOCK_STREAM 1)
        (SOL_SOCKET 65535)
        (SO_RCVTIMEO 4102)
        (SO_SNDTIMEO 4101)
        (SO_REUSEADDR 4)
        (SIGTERM 15)
        (SIGKILL 9)
        (SIGINT 2)
        (SIGHUP 1)
        (SIGCHLD 20)
        (SIGPIPE 13)
        (WNOHANG 1)
        (RLIMIT_CPU 0)
        (RLIMIT_AS 5)
        (POSIX_SPAWN_SETSID 1024)
        (POSIX_SPAWN_CLOEXEC_DEFAULT 16384)
        (POSIX_SPAWN_SETPGROUP 2)
        (CTL_KERN 1)
        (KERN_PROC 14)
        (KERN_PROC_PID 1)
        (EPERM 1)
        (ENOENT 2)
        (ESRCH 3)
        (EINTR 4)
        (EIO 5)
        (EBADF 9)
        (ECHILD 10)
        (EAGAIN 35)
        (EWOULDBLOCK 35)
        (EACCES 13)
        (EEXIST 17)
        (ENOTDIR 20)
        (EISDIR 21)
        (EINVAL 22)
        (EMFILE 24)
        (ENOTTY 25)
        (ENOSPC 28)
        (EROFS 30)
        (EPIPE 32)
        (ENAMETOOLONG 63)
        (ENOTEMPTY 66)
        (ELOOP 62)
        (EOVERFLOW 84)
        (ETIMEDOUT 60)
        (ECONNREFUSED 61)
        (ENOTSOCK 38)
        ))))

  ;; ---- which row is this platform's -----------------------------------------

  ;; A reading's own lines name its platform: (system "Linux"), (machine
  ;; "x86_64"), (libc "glibc 2.39"). -> (system machine libc), libc being
  ;; the library's family ("glibc", "musl") on Linux and #f elsewhere, where
  ;; the system has one C library.
  (define (reading-string r name)
    (let ((e (assq name r)))
      (and e (pair? (cdr e)) (string? (cadr e)) (cadr e))))

  (define (first-word s)
    (let loop ((i 0))
      (cond ((= i (string-length s)) s)
            ((char=? (string-ref s i) #\space) (substring s 0 i))
            (else (loop (+ i 1))))))

  (define (reading-key r)
    (let ((system (reading-string r 'system)))
      (list system
            (reading-string r 'machine)
            (and (equal? system "Linux")
                 (let ((libc (reading-string r 'libc))) (and libc (first-word libc)))))))

  (define (has-prefix? prefix s)
    (and (<= (string-length prefix) (string-length s))
         (string=? (substring s 0 (string-length prefix)) prefix)))

  (define (has-suffix? suffix s)
    (and (<= (string-length suffix) (string-length s))
         (string=? (substring s (- (string-length s) (string-length suffix)) (string-length s)) suffix)))

  ;; -> the last component of a mapping's path, or #f for a line with no
  ;; path. A maps line is address, permissions, offset, device, inode, then
  ;; the pathname; only the pathname holds a "/", so it starts at the
  ;; line's first "/". The kernel appends " (deleted)" to an unlinked
  ;; object's path, and that suffix is not part of its name.
  (define (mapping-basename line)
    (let loop ((i 0))
      (cond
        ((= i (string-length line)) #f)
        ((char=? (string-ref line i) #\/)
         (let* ((path (substring line i (string-length line)))
                (path (if (has-suffix? " (deleted)" path)
                          (substring path 0 (- (string-length path) 10))
                          path)))
           (let last ((j (string-length path)))
             (if (char=? (string-ref path (- j 1)) #\/)
                 (substring path j (string-length path))
                 (last (- j 1))))))
        (else (loop (+ i 1))))))

  (define (text-lines text)
    (let loop ((i 0) (from 0) (out '()))
      (cond ((= i (string-length text)) (reverse (if (< from i) (cons (substring text from i) out) out)))
            ((char=? (string-ref text i) #\newline) (loop (+ i 1) (+ i 1) (cons (substring text from i) out)))
            (else (loop (+ i 1) from out)))))

  ;; THE C LIBRARY ON LINUX, IDENTIFIED POSITIVELY from the objects mapped
  ;; into this very process: glibc's libc.so.6 or its loader ld-linux-*,
  ;; musl's ld-musl-* or libc.musl-*. Each mapping's path is judged by its
  ;; LAST COMPONENT only, so a directory that happens to be named like a
  ;; library (/opt/libc.so.6-build/bin/scheme) names nothing. A text that
  ;; names both families, or neither, reads as unknown, and so does a
  ;; process that cannot read the file (a sandbox hiding /proc) or maps
  ;; neither (a static executable): unknown is unlisted and refused, the
  ;; safe side. -> "glibc", "musl" or "unknown"
  (define (maps-libc text)
    (let* ((names (filter (lambda (b) b) (map mapping-basename (text-lines text))))
           (glibc (exists (lambda (b) (or (string=? b "libc.so.6") (has-prefix? "ld-linux-" b))) names))
           (musl (exists (lambda (b) (or (has-prefix? "ld-musl-" b) (has-prefix? "libc.musl-" b))) names)))
      (cond ((and glibc (not musl)) "glibc")
            ((and musl (not glibc)) "musl")
            (else "unknown"))))

  (define (linux-libc)
    (let ((maps (guard (e (#t #f))
                  (call-with-input-file "/proc/self/maps" get-string-all))))
      (if (string? maps) (maps-libc maps) "unknown")))

  ;; THE SYSTEM AND THE ARCHITECTURE FROM (machine-type), a fixed map.
  ;; Threaded and non-threaded builds map alike: a layout does not depend
  ;; on threads. macOS on x86_64 maps to its own key, Darwin/x86_64, which
  ;; has no row -- it is refused, never given the arm64 row, and that
  ;; covers a Chez built for x86_64 running under Rosetta. Any other
  ;; machine type is unlisted by construction.
  (define (running-key)
    (let* ((m (machine-type))
           (pair (case m
                   ((ta6le a6le) '("Linux" "x86_64"))
                   ((tarm64le arm64le) '("Linux" "aarch64"))
                   ((ta6fb a6fb) '("FreeBSD" "amd64"))
                   ((tarm64osx arm64osx) '("Darwin" "arm64"))
                   ((ta6osx a6osx) '("Darwin" "x86_64"))
                   (else (list "unknown" (symbol->string m))))))
      (list (car pair) (cadr pair)
            (and (equal? (car pair) "Linux") (linux-libc)))))

  ;; Read by the process doing the EXPANDING, as ffi.sc reads its switch:
  ;; the seam below exists only in a build expanded with
  ;; THEOURGIA_INJECT=on, and a build without it has no code that reads
  ;; THEOURGIA_PLATFORM_KEY at all.
  (meta define inject-mode
    (let ((v (getenv "THEOURGIA_INJECT")))
      (cond
        ((or (not v) (string=? v "off")) 'off)
        ((string=? v "on") 'on)
        (else (assertion-violation 'theourgia-platform-numbers
                "THEOURGIA_INJECT must be \"on\", \"off\", or unset" v)))))

  (define (split-slashes s)
    (let loop ((i 0) (from 0) (out '()))
      (cond ((= i (string-length s)) (reverse (cons (substring s from i) out)))
            ((char=? (string-ref s i) #\/) (loop (+ i 1) (+ i 1) (cons (substring s from i) out)))
            (else (loop (+ i 1) from out)))))

  ;; THE TEST SEAM: THEOURGIA_PLATFORM_KEY=<system>/<machine>[/<libc>]
  ;; replaces the whole key, so a row of the suite can run a FRESH child
  ;; as if on another platform (its layouts are then built and read back
  ;; as bytes, never handed to this kernel). It is read once, here, at
  ;; initialisation, so a row once selected is never changed in place.
  (meta-cond
    ((eq? inject-mode 'on)
     (define (forced-key)
       (let ((v (getenv "THEOURGIA_PLATFORM_KEY")))
         (and v (> (string-length v) 0)
              (let ((parts (split-slashes v)))
                (list (car parts)
                      (if (pair? (cdr parts)) (cadr parts) "")
                      (if (and (pair? (cdr parts)) (pair? (cddr parts))) (caddr parts) #f)))))))
    (else
     (define (forced-key) #f)))

  (define selected-key (or (forced-key) (running-key)))

  (define selected
    (let ((row (find (lambda (r) (equal? (reading-key r) selected-key)) readings)))
      (or row
          (let ((p (current-error-port)))
            (write (append (list 'error 'platform-unmeasured
                                 (list 'system (car selected-key))
                                 (list 'machine (cadr selected-key)))
                           (if (caddr selected-key) (list (list 'libc (caddr selected-key))) '())
                           (list (list 'remedy "run test/probe/layout.c and add its row")))
                   p)
            (newline p)
            (flush-output-port p)
            (exit 75)))))

  ;; ---- the accessors ----------------------------------------------------------

  (define (platform-key) selected-key)
  (define (platform-row) selected)
  (define (platform-readings) readings)

  (define (block name)
    (find (lambda (d) (and (pair? d) (eq? (car d) name))) selected))

  (define (struct-block who name)
    (let ((b (find (lambda (d) (and (pair? d) (eq? (car d) 'struct) (pair? (cdr d)) (eq? (cadr d) name)))
                   selected)))
      (cond ((not b) (assertion-violation who "no such struct in the platform table" name))
            ((equal? (cddr b) '(absent)) (assertion-violation who "struct absent on this platform" name selected-key))
            (else (cddr b)))))

  (define (entry-value who entries key what)
    (let ((e (assq key entries)))
      (unless (and e (pair? (cdr e)) (exact? (cadr e)) (integer? (cadr e)))
        (assertion-violation who "no such entry in the platform table" what key))
      (cadr e)))

  ;; -> the exact integer the row's (constants ...) block gives for NAME.
  (define (platform-number name)
    (let* ((c (block 'constants))
           (e (and c (assq name (cdr c)))))
      (cond ((not e) (assertion-violation 'platform-number "no such number in the platform table" name))
            ((eq? (cadr e) 'absent) (assertion-violation 'platform-number "absent on this platform" name selected-key))
            (else (cadr e)))))

  (define (struct-size who name)
    (entry-value who (struct-block who name) 'size name))

  (define (platform-struct-size name) (struct-size 'platform-struct-size name))

  (define (field-entry who sname fname)
    (let ((f (find (lambda (d) (and (pair? d) (eq? (car d) 'field) (pair? (cdr d)) (eq? (cadr d) fname)))
                   (struct-block who sname))))
      (unless f (assertion-violation who "no such field in the platform table" sname fname))
      f))

  ;; -> #t when the row has the field, #f when it prints it absent
  ;; (sun_len and d_namlen on Linux).
  (define (platform-field-present? sname fname)
    (not (equal? (cddr (field-entry 'platform-field-present? sname fname)) '(absent))))

  ;; -> the field's offset or size; a field the row prints absent is a
  ;; programming error here: its presence is asked first.
  (define (platform-field sname fname what)
    (let ((f (field-entry 'platform-field sname fname)))
      (when (equal? (cddr f) '(absent))
        (assertion-violation 'platform-field "field absent on this platform" sname fname selected-key))
      (entry-value 'platform-field (cddr f) what (list sname fname))))

  ;; -> a value a struct block states directly, as posix_spawn's
  ;; (attr-size n) and (file-actions-size n).
  (define (platform-struct-value sname key)
    (entry-value 'platform-struct-value (struct-block 'platform-struct-value sname) key sname))

  ;; -> a (types ...) entry's size: pid_t, int.
  (define (platform-type-size name)
    (let* ((b (block 'types))
           (e (and b (assq name (cdr b)))))
      (unless e (assertion-violation 'platform-type-size "no such type in the platform table" name))
      (entry-value 'platform-type-size (cdr e) 'size name)))

  ;; -> one of the (wait-status ...) samples the probe computed with the
  ;; platform's own macros, which check the decoding kept in ffi.sc.
  (define (platform-wait-sample name)
    (let ((b (block 'wait-status)))
      (unless b (assertion-violation 'platform-wait-sample "no wait-status block" selected-key))
      (entry-value 'platform-wait-sample (cdr b) name 'wait-status)))
)
