#!r6rs
;; Copyright 2026 guenchi
;;
;; Licensed under the Apache License, Version 2.0 (the "License");
;; you may not use this file except in compliance with the License.
;; You may obtain a copy of the License at
;;
;;     http://www.apache.org/licenses/LICENSE-2.0
;;
;; Unless required by applicable law or agreed to in writing, software
;; distributed under the License is distributed on an "AS IS" BASIS,
;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;; See the License for the specific language governing permissions and
;; limitations under the License.
(library (theourgia regex)
  (export regex-compile regex-match)
  (import (rnrs))

  ;; A bounded regular-expression subset for data-driven definition heads.
  ;; No numeric reader, backreferences, lookarounds or host regex dependency.
  (define (regex-compile source)
    (let ((i 0) (n (string-length source)) (groups 0))
      (define (peek) (and (< i n) (string-ref source i)))
      (define (take!) (let ((c (peek))) (set! i (+ i 1)) c))
      (define (expect! c)
        (unless (eqv? (take!) c) (assertion-violation 'regex "Malformed pattern" source)))
      (define (escaped!)
        (let ((c (take!)))
          (case c ((#\s) 'space) ((#\d) 'digit) ((#\w) 'word)
                ((#\n) #\newline) ((#\r) #\return) ((#\t) #\tab)
                (else (if c c (assertion-violation 'regex "Trailing escape" source))))))
      (define (class!)
        (let ((negate? (eqv? (peek) #\^)))
          (when negate? (take!))
          (let loop ((out '()))
            (cond
              ((not (peek)) (assertion-violation 'regex "Unclosed class" source))
              ((eqv? (peek) #\]) (take!) (list 'class negate? (reverse out)))
              (else
               (let ((a (if (eqv? (peek) #\\) (begin (take!) (escaped!)) (take!))))
                 (if (and (char? a) (eqv? (peek) #\-) (< (+ i 1) n)
                          (not (char=? (string-ref source (+ i 1)) #\])))
                     (begin (take!)
                            (let ((b (if (eqv? (peek) #\\) (begin (take!) (escaped!)) (take!))))
                              (unless (char? b) (assertion-violation 'regex "Invalid range" source))
                              (loop (cons (cons a b) out))))
                     (loop (cons a out)))))))))
      (define (atom!)
        (let ((c (take!)))
          (case c
            ((#\() (let ((capture? #t))
                     (when (eqv? (peek) #\?) (take!) (expect! #\:) (set! capture? #f))
                     (when capture? (set! groups (+ groups 1)))
                     (let* ((index groups) (body (alternative!)))
                       (expect! #\)) (if capture? (list 'group index body) body))))
            ((#\[) (class!))
            ((#\\) (list 'class #f (list (escaped!))))
            ((#\^) '(start)) ((#\$) '(end)) ((#\.) '(any))
            (else (list 'char c)))))
      (define (repeated!)
        (let ((a (atom!)))
          (if (memv (peek) '(#\* #\+ #\?))
              (let* ((q (take!)) (lazy? (eqv? (peek) #\?)))
                (when lazy? (take!))
                (list 'repeat (if (eqv? q #\+) 1 0) (if (eqv? q #\?) 1 #f) (not lazy?) a)) a)))
      (define (sequence!)
        (let loop ((out '()))
          (if (or (not (peek)) (memv (peek) '(#\) #\|))) (cons 'seq (reverse out))
              (loop (cons (repeated!) out)))))
      (define (alternative!)
        (let loop ((out (list (sequence!))))
          (if (eqv? (peek) #\|) (begin (take!) (loop (cons (sequence!) out)))
              (cons 'alt (reverse out)))))
      (let ((ast (alternative!)))
        (unless (= i n) (assertion-violation 'regex "Unmatched parenthesis" source)) ast)))

  (define (regex-match ast text . spans)
    (let ((n (string-length text)) (budget 30000))
      (define (tick!)
        (set! budget (- budget 1))
        (when (< budget 0) (assertion-violation 'regex-limit "Pattern work limit exceeded")))
      (define (matches? item c)
        (cond ((char? item) (char=? item c))
              ((pair? item) (char<=? (car item) c (cdr item)))
              ((eq? item 'space) (memv c '(#\space #\tab #\newline #\return #\page)))
              ((eq? item 'digit) (char<=? #\0 c #\9))
              ((eq? item 'word) (or (char<=? #\a c #\z) (char<=? #\A c #\Z)
                                    (char<=? #\0 c #\9) (char=? c #\_)))
              (else #f)))
      (define (run pattern state)
        (tick!)
        (let ((pos (car state)) (captures (cdr state)))
          (define (consume yes?) (if (and (< pos n) yes?) (list (cons (+ pos 1) captures)) '()))
          (case (car pattern)
            ((start) (if (= pos 0) (list state) '()))
            ((end) (if (= pos n) (list state) '()))
            ((char) (consume (and (< pos n) (char=? (cadr pattern) (string-ref text pos)))))
            ((any) (consume (and (< pos n) (not (memv (string-ref text pos) '(#\newline #\return))))))
            ((class) (consume (and (< pos n)
                              (not (eq? (and (exists (lambda (x) (matches? x (string-ref text pos))) (caddr pattern)) #t)
                                        (cadr pattern))))))
            ((alt) (apply append (map (lambda (p) (run p state)) (cdr pattern))))
            ((seq) (let loop ((ps (cdr pattern)) (states (list state)))
                     (if (null? ps) states
                         (loop (cdr ps) (apply append (map (lambda (s) (run (car ps) s)) states))))))
            ((group) (map (lambda (s)
                            (cons (car s) (cons (cons (cadr pattern) (cons pos (car s)))
                                                (filter (lambda (p) (not (= (car p) (cadr pattern)))) (cdr s)))))
                          (run (caddr pattern) state)))
            ((repeat)
             (let ((min (cadr pattern)) (max (caddr pattern)) (greedy? (cadddr pattern)) (body (list-ref pattern 4)))
               (let loop ((state state) (count 0))
                 (tick!)
                 (let* ((here (if (>= count min) (list state) '()))
                        (later (if (and max (>= count max)) '()
                                   (apply append
                                     (map (lambda (s) (loop s (+ count 1)))
                                          (filter (lambda (s) (> (car s) (car state))) (run body state)))))))
                   (if greedy? (append later here) (append here later))))))
            (else (assertion-violation 'regex "Unknown compiled operator" (car pattern))))))
      (when (> n 4096) (assertion-violation 'regex-limit "Definition line exceeds limit"))
      (let ((matches (run ast (cons 0 '()))))
        (and (pair? matches)
             (if (pair? spans) (cdar matches)
                 (map (lambda (p) (cons (car p) (substring text (cadr p) (cddr p)))) (cdar matches)))))))
)
