#!r6rs
;; Copyright 2026 guenchi
;;
;; Licensed under the Apache License, Version 2.0 (the "License");
;; you may not use this file except in compliance with the License.
;; You may obtain a copy of the License at
;;
;;     http://www.apache.org/licenses/LICENSE-2.0
;;
;; Unless required by applicable law or agreed to in writing, software
;; distributed under the License is distributed on an "AS IS" BASIS,
;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;; See the License for the specific language governing permissions and
;; limitations under the License.
(library (theourgia working)
  (export working-write! working-read working-discard! working-list working-commit!)
  (import (rnrs) (theourgia store) (theourgia reduce) (theourgia baseline)
          (theourgia wire) (theourgia digest)
          (only (theourgia log) store-writers writer-directory atomic-write!
                directory-entry-durable!)
          (only (theourgia ffi) directory-entries file-is-directory? mkdir-p!
                process-id wall-clock-ms unlink!))

  (define counter 0)
  (define (fresh-id)
    (set! counter (+ counter 1))
    (string-append "w-" (number->string (process-id)) "-"
                   (number->string (wall-clock-ms)) "-" (number->string counter)))
  (define (encode x)
    (string->utf8 (sexpr->string-extended (storable-encode x))))
  (define (decode-file path)
    (call-with-port (open-file-input-port path)
      (lambda (p) (storable-decode (string->sexpr-extended (utf8->string (get-bytevector-all p)))))))
  (define (digest x) (bytevector->hex (sha256 (encode x))))
  (define (safe-id? x)
    (and (string? x) (> (string-length x) 0) (<= (string-length x) 128)
         (for-all (lambda (c) (or (char<=? #\a c #\z) (char<=? #\0 c #\9)
                                  (memv c '(#\- #\_ #\.)))) (string->list x))
         (not (member x '("." "..")))))
  (define (writer-for store supplied)
    (cond
      (supplied (and (safe-id? supplied) supplied))
      (else (find (lambda (w)
                    (and (file-exists? (string-append (writer-directory store w) "/owner.sexp"))
                         (not (file-exists? (string-append (writer-directory store w) "/retired.sexp")))))
                  (store-writers store)))))
  (define (block-name? name)
    (and (safe-id? name)
         (= 1 (length (filter (lambda (c) (char=? c #\.)) (string->list name))))
         (not (char=? #\. (string-ref name 0)))
         (not (char=? #\. (string-ref name (- (string-length name) 1))))))
  (define (area store writer name)
    (string-append (writer-directory store writer) "/" name))
  (define (ensure-area! store writer name)
    (let ((dir (area store writer name)))
      (mkdir-p! dir)
      (directory-entry-durable! (writer-directory store writer) 'working)
      (directory-entry-durable! dir 'working)
      dir))
  (define (path-for store writer id) (string-append (area store writer "working") "/" id))
  (define (entry? x)
    (and (list? x) (= (length x) 8) (eq? (car x) 'working) (equal? (cadr x) 1)
         (safe-id? (list-ref x 2)) (safe-id? (list-ref x 3))
         (string? (list-ref x 4)) (string? (list-ref x 5))
         (list? (list-ref x 6)) (bytevector? (list-ref x 7))))
  (define (entry-at store writer id)
    (let ((p (path-for store writer id)))
      (and (file-exists? p)
           (let ((x (decode-file p)))
             (unless (and (entry? x) (equal? writer (list-ref x 2)) (equal? id (list-ref x 3)))
               (assertion-violation 'working "Corrupt working envelope" p))
             x))))
  (define (field state id name)
    (let* ((b (state-read state id)) (fs (and b (assq 'fields b)))
           (v (and fs (assq name (cdr fs)))))
      (and v (cdr v))))
  (define (problem thunk)
    (guard (e (#t (list 'error 'working-unavailable
                        (list 'message (if (message-condition? e) (condition-message e) "Working storage failed")))))
      (thunk)))
  (define (invalid-writer) '(error bad-request invalid-working-writer))

  ;; One immutable packet binds a request to the exact versions it sent.
  ;; It is durable before execution; no post-commit marker is required to
  ;; distinguish a consumed leftover from a later write of identical bytes.
  (define (packet? x)
    (and (list? x) (= (length x) 5) (eq? (car x) 'working-packet)
         (equal? (cadr x) 1) (write-request? (list-ref x 2))
         (write-request? (list-ref x 3)) (list? (list-ref x 4))
         (for-all entry? (list-ref x 4))))
  (define (packets store writer)
    (let ((dir (area store writer "working-requests")))
      (if (not (file-is-directory? dir)) '()
          (map (lambda (name)
                 (let ((x (decode-file (string-append dir "/" name))))
                   (unless (packet? x) (assertion-violation 'working "Corrupt commit packet" name))
                   x))
               (filter (lambda (n) (and (> (string-length n) 5)
                                  (string=? ".sexp" (substring n (- (string-length n) 5) (string-length n)))))
                       (directory-entries dir))))))
  (define (packet-verdict store state packet)
    (request-verdict store (list-ref packet 3) (reduce-applied-cut state)
                     (let ((n (length (list-ref packet 4)))) (and (not (= n 1)) n))
                     (reduce-gates state) 'plan))
  (define (consumed? store state entry ps)
    (exists (lambda (p)
              (and (member entry (list-ref p 4))
                   (eq? 'replay (car (packet-verdict store state p))))) ps))
  (define (active-entries store writer state)
    (let ((dir (area store writer "working")) (ps (packets store writer)))
      (if (not (file-is-directory? dir)) '()
          (filter (lambda (e) (not (consumed? store state e ps)))
            (map (lambda (id) (entry-at store writer id))
                 (filter block-name? (list-sort string<? (directory-entries dir))))))))

  ;; A committed parent advances a sequential edit only to that execution's
  ;; causal cut. A later external edit is never adopted as its baseline.
  (define (committed-parent store state writer id version hash original-cut)
    (and writer version (safe-id? writer)
      (exists
        (lambda (packet)
          (let ((entries (list-ref packet 4)))
            (and (= (length entries) 1)
              (let ((entry (car entries)))
                (and (equal? id (list-ref entry 3)) (equal? version (list-ref entry 4))
                     (equal? hash (list-ref entry 5)) (equal? original-cut (list-ref entry 6))
                  (let ((verdict (packet-verdict store state packet)))
                    (and (eq? (car verdict) 'replay)
                      (let ((cut (state-event-cut state (cadr verdict))))
                        (and cut (let ((past (open-and-reduce store cut)))
                          (and (reduction? past) past)))))))))))
        (packets store writer))))

  (define (working-write! store supplied id bytes rebase? . provenance)
    (problem
      (lambda ()
        (let* ((writer (writer-for store supplied)) (state (open-and-reduce store))
               (hash (and (pair? provenance) (car provenance)))
               (cut-text (and (pair? provenance) (pair? (cdr provenance)) (cadr provenance)))
               (parent-writer (and (>= (length provenance) 4) (list-ref provenance 2)))
               (parent-version (and (>= (length provenance) 4) (list-ref provenance 3)))
               (historical (and hash cut-text
                 (guard (failure (#t #f))
                   (let ((parsed (parse-cut cut-text))) (and parsed (open-and-reduce store parsed))))))
               (parent (and (reduction? historical)
                            (committed-parent store state parent-writer id parent-version hash (reduce-applied-cut historical)))))
          (cond
            ((not writer) (invalid-writer))
            ((not (safe-id? id)) '(error bad-request invalid-block-id))
            ((not (state-read state id)) (list 'error 'unknown-id id))
            ((and (or parent-writer parent-version)
                  (not (and parent-writer parent-version hash cut-text (safe-id? parent-writer))))
             '(error invalid-working-baseline))
            ((and (or hash cut-text)
                  (not (and (reduction? historical) (state-read historical id)
                            (equal? hash (block-hash historical id)))))
             '(error invalid-working-baseline))
            (else
             (let* ((old (entry-at store writer id))
                    (reuse (and old (not rebase?) (not (consumed? store state old (packets store writer)))))
                    (entry (list 'working 1 writer id (fresh-id)
                                 (cond (reuse (list-ref old 5)) ((and parent (not rebase?)) (block-hash parent id))
                                       ((and historical (not rebase?)) hash)
                                       (else (block-hash state id)))
                                 (cond (reuse (list-ref old 6)) ((and parent (not rebase?)) (reduce-applied-cut parent))
                                       ((and historical (not rebase?)) (reduce-applied-cut historical))
                                       (else (reduce-applied-cut state)))
                                 (if (string? bytes) (string->utf8 bytes) bytes))))
               (unless (bytevector? (list-ref entry 7)) (assertion-violation 'write "Expected bytes" bytes))
               (ensure-area! store writer "working")
               (atomic-write! (path-for store writer id) (encode entry) 'working)
               (list 'ok (list 'saved id) (list 'writer writer)
                     (list 'version (list-ref entry 4)) (list 'based-on (list-ref entry 5))))))))))

  (define (working-read store supplied id . information)
    (problem (lambda ()
      (let ((writer (writer-for store supplied)) (state (open-and-reduce store)))
        (if (not writer) (invalid-writer)
            (let* ((e (and (safe-id? id) (entry-at store writer id)))
                   (active (and e (not (consumed? store state e (packets store writer)))))
                   (body (if active (list-ref e 7) (or (field state id 'src) ""))))
              (cond
                ((not (state-read state id)) (list 'error 'unknown-id id))
                (else
                  (let* ((b (if (string? body) (string->utf8 body) body))
                         (s (guard (failure (#t #f)) (utf8->string b)))
                         (text (and s (equal? b (string->utf8 s)) s)))
                    (if (and (pair? information) (car information))
                        (if text
                            (list 'ok (list 'projection (if active 'working 'committed) writer id
                              (and active (list-ref e 4))
                              (if active (list-ref e 5) (block-hash state id))
                              (if active (list-ref e 6) (reduce-applied-cut state)) text
                              (string-append (or (field state id 'front) "") (or (field state id 'heading-src) ""))))
                            '(error working-unavailable non-text-projection))
                        (if text (list 'ok (list 'text text)) (list 'ok (list 'bytes b)))))))))))))

  (define (working-discard! store supplied id)
    (problem (lambda ()
      (let ((writer (writer-for store supplied)))
        (cond ((not writer) (invalid-writer))
              ((not (safe-id? id)) '(error bad-request invalid-block-id))
              (else (let ((p (path-for store writer id)))
                      (when (file-exists? p) (unlink! p) (directory-entry-durable! p 'working))
                      (list 'ok (list 'discarded id)))))))))

  (define (working-list store supplied)
    (problem (lambda ()
      (let ((writer (writer-for store supplied)) (state (open-and-reduce store)))
        (if (not writer) (invalid-writer)
            (list 'ok (cons 'items
              (map (lambda (e)
                     (list 'draft (list 'block (list-ref e 3)) (list 'writer writer)
                           (list 'version (list-ref e 4)) (list 'based-on (list-ref e 5))
                           (list 'now (block-hash state (list-ref e 3)))
                           (list 'fresh (equal? (list-ref e 5) (block-hash state (list-ref e 3))))))
                   (active-entries store writer state)))))))))

  (define (preflight state entries)
    (let ((bad (filter values
                 (map (lambda (e) (baseline-refusal state (list-ref e 3) (list-ref e 5) (list-ref e 6))) entries))))
      (cond ((null? bad) #f)
            ((null? (cdr bad)) (car bad))
            (else (list 'error 'stale-baseline (cons 'blocks (map cddr bad)))))))
  (define (entry-intent e)
    (let* ((bytes (list-ref e 7)) (text (utf8->string bytes)))
      (unless (equal? bytes (string->utf8 text))
        (assertion-violation 'commit "The src field requires valid UTF-8" (list-ref e 3)))
      (list 'set (list-ref e 3) 'src text)))
  (define (ticket-path store writer req)
    (string-append (area store writer "working-requests") "/"
                   (digest (list (car (list-ref req 5)) (list-ref req 4))) ".sexp"))
  (define (retire! store writer entries)
    (for-each (lambda (e)
                (guard (failure (#t #f))
                  (when (equal? e (entry-at store writer (list-ref e 3)))
                    (working-discard! store writer (list-ref e 3))))) entries))

  (define (working-commit! store supplied ids actor supplied-req . selected-version)
    (problem (lambda ()
      (let* ((writer (writer-for store supplied)) (state (open-and-reduce store)))
        (cond
          ((not writer) (invalid-writer))
          ((not (for-all safe-id? ids)) '(error bad-request invalid-block-id))
          ((not (= (length ids) (length (list-sort string<? (let loop ((xs ids) (out '()))
                                      (if (null? xs) out (loop (cdr xs) (if (member (car xs) out) out (cons (car xs) out)))))))))
           '(error bad-request duplicate-block))
          (else
           (let* ((after (or (assoc (writer-for store #f) (reduce-applied-cut state))
                             (cons (writer-for store #f) 0)))
                  (external (or supplied-req (make-write-request actor 'commit ids (fresh-id) after)))
                  (path (ticket-path store writer external))
                  (saved (and (file-exists? path) (decode-file path))))
             (cond
               ((and saved (not (packet? saved))) '(error working-unavailable corrupt-commit-packet))
               ((and saved (not (equal? external (list-ref saved 2)))) '(error req-mismatch))
               (else
                (let* ((entries (if saved (list-ref saved 4)
                                    (let ((all (active-entries store writer state)))
                                      (if (null? ids) all
                                          (filter (lambda (e) (member (list-ref e 3) ids)) all)))))
                       (missing (filter (lambda (id) (not (exists (lambda (e) (equal? id (list-ref e 3))) entries))) ids))
                       (intents (map entry-intent entries))
                       (effective (if saved (list-ref saved 3)
                                      (make-write-request actor 'commit
                                        (append (list-ref external 3) (list (utf8->string (encode entries))))
                                        (list-ref external 4) (list-ref external 5)))))
                  (cond
                    ((and (not saved) (pair? missing)) (list 'error 'no-draft (cons 'blocks missing)))
                    ((and (not saved) (pair? selected-version) (car selected-version)
                          (not (and (= (length ids) 1) (= (length entries) 1)
                                    (equal? (car selected-version) (list-ref (car entries) 4)))))
                     (list 'error 'working-version-changed (cons 'blocks ids)))
                    ((and (not supplied-req) (null? entries)) '(ok (items)))
                    (else
                     (unless saved
                       (ensure-area! store writer "working-requests")
                       (atomic-write! path (encode (list 'working-packet 1 external effective entries)) 'working))
                     (let ((answers (with-store-write store (lambda (current view) intents)
                                      actor effective (lambda (current) (preflight current entries)) #t)))
                       (if (for-all (lambda (a) (and (pair? a) (eq? (car a) 'ok))) answers)
                           (begin (retire! store writer entries) (list 'ok (cons 'items answers)))
                           (if (= (length answers) 1) (car answers) (list 'batch answers))))))))))))))))
)
