;; The $INODE64 symbols macOS exports for x86_64-macos, read 2026-10-01 from the
;; Xcode SDK's usr/lib/system/libsystem_c.tbd and libsystem_kernel.tbd
;; (dyld_info -arch x86_64 -exports on libsystem_kernel.dylib, this machine,
;; gives the same seven of the latter). Each is the C name without the
;; symbol's leading underscore; the symbol bound is the name plus $INODE64.
("__opendir2"
 "_readdir_unlocked"
 "_seekdir"
 "alphasort"
 "fdopendir"
 "fdscandir"
 "fdscandir_b"
 "fstat"
 "fstatat"
 "fstatfs"
 "fstatx_np"
 "fts_children"
 "fts_close"
 "fts_open"
 "fts_open_b"
 "fts_read"
 "fts_set"
 "ftw"
 "getfsstat"
 "getmntinfo"
 "getmntinfo_r_np"
 "glob"
 "glob_b"
 "lstat"
 "lstatx_np"
 "nftw"
 "opendir"
 "readdir"
 "readdir_r"
 "rewinddir"
 "scandir"
 "scandir_b"
 "scandirat"
 "scandirat_b"
 "seekdir"
 "stat"
 "statfs"
 "statx_np"
 "telldir")
