(layout-probe 4)
(machine "amd64") (system "FreeBSD") (release "15.0-RELEASE")
(libc "freebsd 15")
(pointer-size 8)
(struct stat (size 224)
  (field st_dev (offset 0) (size 8))
  (field st_ino (offset 8) (size 8))
  (field st_mode (offset 24) (size 2))
  (field st_nlink (offset 16) (size 8))
  (field st_uid (offset 28) (size 4))
  (field st_gid (offset 32) (size 4))
  (field st_size (offset 112) (size 8))
  (field st_blksize (offset 128) (size 4))
  (field st_blocks (offset 120) (size 8))
  (field st_atim (member st_atim) (offset 48) (size 16))
  (field st_mtim (member st_mtim) (offset 64) (size 16))
  (field st_ctim (member st_ctim) (offset 80) (size 16))
  (type dev_t (size 8))
  (type ino_t (size 8))
  (type mode_t (size 2))
  (type nlink_t (size 8))
  (type uid_t (size 4))
  (type gid_t (size 4))
  (type off_t (size 8))
  (type blksize_t (size 4))
  (type blkcnt_t (size 8))
  (type time_t (size 8))
  (type struct timespec (size 16))
  (field-of-timespec tv_nsec (offset 8) (size 8)))
(struct sockaddr_un (size 106)
  (field sun_len (offset 0) (size 1))
  (field sun_family (offset 1) (size 1))
  (field sun_path (offset 2) (size 104))
  (type sa_family_t (size 1))
  (af-unix 1)
  (sun-len "/nonexistent/theourgia-layout-probe/socket" 44))
(struct dirent (size 280)
  (field d_ino (offset 0) (size 8))
  (field d_type (offset 18) (size 1))
  (field d_namlen (offset 20) (size 2))
  (field d_reclen (offset 16) (size 2))
  (field d_name (offset 24) (size 256))
  )
(struct timeval (size 16)
  (field tv_sec (offset 0) (size 8))
  (field tv_usec (offset 8) (size 8))
  )
(struct rlimit (size 16)
  (field rlim_cur (offset 0) (size 8))
  (field rlim_max (offset 8) (size 8))
  (RLIM_INFINITY 9223372036854775807))
(types (pid_t (size 4)) (int (size 4)))
(struct proc_taskinfo absent)
(struct kinfo_proc (size 1088)
  (field ki_rssize (offset 264) (size 8))
  )
(struct posix_spawn (attr-size 8) (file-actions-size 8))
(wait-status (WEXITSTATUS-0x0300 3) (WIFEXITED-0x0300 1) (WTERMSIG-0x0009 9) (WIFSIGNALED-0x0009 1))
(constants
  (X_OK 1)
  (F_OK 0)
  (PATH_MAX 1024)
  (PROC_PIDTASKINFO absent)
  (O_RDONLY 0)
  (O_WRONLY 1)
  (O_RDWR 2)
  (O_CREAT 512)
  (O_TRUNC 1024)
  (O_EXCL 2048)
  (O_APPEND 8)
  (O_CLOEXEC 1048576)
  (O_NOFOLLOW 256)
  (O_DIRECTORY 131072)
  (O_NONBLOCK 4)
  (FIOCLEX 536897025)
  (FIONCLEX 536897026)
  (F_GETFD 1)
  (F_SETFD 2)
  (FD_CLOEXEC 1)
  (F_GETFL 3)
  (F_SETFL 4)
  (F_DUPFD 0)
  (F_FULLFSYNC absent)
  (_SC_NPROCESSORS_ONLN 58)
  (_SC_PAGESIZE 47)
  (_PC_CASE_SENSITIVE absent)
  (LOCK_SH 1)
  (LOCK_EX 2)
  (LOCK_NB 4)
  (LOCK_UN 8)
  (SEEK_SET 0)
  (SEEK_CUR 1)
  (SEEK_END 2)
  (S_IFMT 61440)
  (S_IFDIR 16384)
  (S_IFREG 32768)
  (S_IFLNK 40960)
  (S_IFSOCK 49152)
  (AF_UNIX 1)
  (SOCK_STREAM 1)
  (SOL_SOCKET 65535)
  (SO_RCVTIMEO 4102)
  (SO_SNDTIMEO 4101)
  (SO_REUSEADDR 4)
  (SIGTERM 15)
  (SIGKILL 9)
  (SIGINT 2)
  (SIGHUP 1)
  (SIGCHLD 20)
  (SIGPIPE 13)
  (WNOHANG 1)
  (RLIMIT_CPU 0)
  (RLIMIT_AS 10)
  (POSIX_SPAWN_SETSID absent)
  (POSIX_SPAWN_CLOEXEC_DEFAULT absent)
  (POSIX_SPAWN_SETPGROUP 2)
  (CTL_KERN 1)
  (KERN_PROC 14)
  (KERN_PROC_PID 1)
  (EPERM 1)
  (ENOENT 2)
  (ESRCH 3)
  (EINTR 4)
  (EIO 5)
  (EBADF 9)
  (ECHILD 10)
  (EAGAIN 35)
  (EWOULDBLOCK 35)
  (EACCES 13)
  (EEXIST 17)
  (ENOTDIR 20)
  (EISDIR 21)
  (EINVAL 22)
  (EMFILE 24)
  (ENOTTY 25)
  (ENOSPC 28)
  (EROFS 30)
  (EPIPE 32)
  (ENAMETOOLONG 63)
  (ENOTEMPTY 66)
  (ELOOP 62)
  (EOVERFLOW 84)
  (ETIMEDOUT 60)
  (ECONNREFUSED 61)
  (ENOTSOCK 38)
  )
