(layout-probe 5)
(machine "x86_64") (system "Linux") (release "6.17.0-1022-azure")
(libc "glibc 2.39")
(pointer-size 8)
(struct stat (size 144)
  (field st_dev (offset 0) (size 8))
  (field st_ino (offset 8) (size 8))
  (field st_mode (offset 24) (size 4))
  (field st_nlink (offset 16) (size 8))
  (field st_uid (offset 28) (size 4))
  (field st_gid (offset 32) (size 4))
  (field st_size (offset 48) (size 8))
  (field st_blksize (offset 56) (size 8))
  (field st_blocks (offset 64) (size 8))
  (field st_atim (member st_atim) (offset 72) (size 16))
  (field st_mtim (member st_mtim) (offset 88) (size 16))
  (field st_ctim (member st_ctim) (offset 104) (size 16))
  (type dev_t (size 8))
  (type ino_t (size 8))
  (type mode_t (size 4))
  (type nlink_t (size 8))
  (type uid_t (size 4))
  (type gid_t (size 4))
  (type off_t (size 8))
  (type blksize_t (size 8))
  (type blkcnt_t (size 8))
  (type time_t (size 8))
  (type struct timespec (size 16))
  (field-of-timespec tv_nsec (offset 8) (size 8)))
(struct sockaddr_un (size 110)
  (field sun_len absent)
  (field sun_family (offset 0) (size 2))
  (field sun_path (offset 2) (size 108))
  (type sa_family_t (size 2))
  (af-unix 1)
  (sun-len "/nonexistent/theourgia-layout-probe/socket" 44))
(struct dirent (size 280)
  (field d_ino (offset 0) (size 8))
  (field d_type (offset 18) (size 1))
  (field d_namlen absent)
  (field d_reclen (offset 16) (size 2))
  (field d_name (offset 19) (size 256))
  )
(struct timeval (size 16)
  (field tv_sec (offset 0) (size 8))
  (field tv_usec (offset 8) (size 8))
  )
(struct rlimit (size 16)
  (field rlim_cur (offset 0) (size 8))
  (field rlim_max (offset 8) (size 8))
  (RLIM_INFINITY 18446744073709551615))
(types (pid_t (size 4)) (int (size 4)))
(struct proc_taskinfo absent)
(struct kinfo_proc absent)
(struct posix_spawn (attr-size 336) (file-actions-size 80))
(wait-status (WEXITSTATUS-0x0300 3) (WIFEXITED-0x0300 1) (WTERMSIG-0x0009 9) (WIFSIGNALED-0x0009 1))
(constants
  (X_OK 1)
  (F_OK 0)
  (PATH_MAX 4096)
  (PROC_PIDTASKINFO absent)
  (O_RDONLY 0)
  (O_WRONLY 1)
  (O_RDWR 2)
  (O_CREAT 64)
  (O_TRUNC 512)
  (O_EXCL 128)
  (O_APPEND 1024)
  (O_CLOEXEC 524288)
  (O_NOFOLLOW 131072)
  (O_DIRECTORY 65536)
  (O_NONBLOCK 2048)
  (FIOCLEX 21585)
  (FIONCLEX 21584)
  (F_GETFD 1)
  (F_SETFD 2)
  (FD_CLOEXEC 1)
  (F_GETFL 3)
  (F_SETFL 4)
  (F_DUPFD 0)
  (F_FULLFSYNC absent)
  (_SC_NPROCESSORS_ONLN 84)
  (_SC_PAGESIZE 30)
  (_PC_CASE_SENSITIVE absent)
  (LOCK_SH 1)
  (LOCK_EX 2)
  (LOCK_NB 4)
  (LOCK_UN 8)
  (SEEK_SET 0)
  (SEEK_CUR 1)
  (SEEK_END 2)
  (S_IFMT 61440)
  (S_IFDIR 16384)
  (S_IFREG 32768)
  (S_IFLNK 40960)
  (S_IFSOCK 49152)
  (AF_UNIX 1)
  (SOCK_STREAM 1)
  (SOL_SOCKET 1)
  (SO_RCVTIMEO 20)
  (SO_SNDTIMEO 21)
  (SO_REUSEADDR 2)
  (SIGTERM 15)
  (SIGKILL 9)
  (SIGINT 2)
  (SIGHUP 1)
  (SIGCHLD 17)
  (SIGPIPE 13)
  (WNOHANG 1)
  (RLIMIT_CPU 0)
  (RLIMIT_AS 9)
  (POSIX_SPAWN_SETSID absent)
  (POSIX_SPAWN_CLOEXEC_DEFAULT absent)
  (POSIX_SPAWN_SETPGROUP 2)
  (CTL_KERN absent)
  (KERN_PROC absent)
  (KERN_PROC_PID absent)
  (KERN_PROC_ENV absent)
  (EPERM 1)
  (ENOENT 2)
  (ESRCH 3)
  (EINTR 4)
  (EIO 5)
  (EBADF 9)
  (ECHILD 10)
  (EAGAIN 11)
  (EWOULDBLOCK 11)
  (EACCES 13)
  (EEXIST 17)
  (ENOTDIR 20)
  (EISDIR 21)
  (EINVAL 22)
  (EMFILE 24)
  (ENOTTY 25)
  (ENOSPC 28)
  (EROFS 30)
  (EPIPE 32)
  (ENAMETOOLONG 36)
  (ENOTEMPTY 39)
  (ELOOP 40)
  (EOVERFLOW 75)
  (ETIMEDOUT 110)
  (ECONNREFUSED 111)
  (ENOTSOCK 88)
  )
